import { useEffect, useMemo, useState } from "react";
import { BriefcaseBusiness, ChevronRight, ClipboardPlus, RefreshCw, Users } from "lucide-react";
import { createCampoAgentePedido, getCampoAgentePainel, listCampoAgenteClientes, listCidades, type CampoAgenteClienteApi, type CampoAgentePainelApi, type CidadeApi } from "@/lib/ajc-api";

const brl = (value:number|null) => value == null ? "—" : value.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});

export function CampoAgente(){
  const [data,setData]=useState<CampoAgentePainelApi|null>(null);
  const [clientes,setClientes]=useState<CampoAgenteClienteApi[]>([]);
  const [cidades,setCidades]=useState<CidadeApi[]>([]);
  const [open,setOpen]=useState(false); const [busy,setBusy]=useState(false); const [message,setMessage]=useState<string|null>(null);
  const [form,setForm]=useState<{tipo:"carga"|"encomenda"|"veiculo"|"maquina";clienteId:string;destinoSigla:string;valor:string;observacao:string}>({tipo:"carga",clienteId:"",destinoSigla:"",valor:"",observacao:""});
  async function load(){setMessage(null);try{const [painel,carteira,cidadesAtivas]=await Promise.all([getCampoAgentePainel(),listCampoAgenteClientes(),listCidades()]);setData(painel);setClientes(carteira);setCidades(cidadesAtivas.filter(c=>c.ativo));}catch(e){setMessage(e instanceof Error?e.message:"Não foi possível carregar sua carteira.");}}
  useEffect(()=>{void load()},[]);
  const destinos=useMemo(()=>cidades.filter(c=>c.sigla!==data?.agente.cidadeSigla),[cidades,data]);
  async function save(){if(!data||!form.clienteId||!form.destinoSigla)return;setBusy(true);setMessage(null);try{await createCampoAgentePedido({tipo:form.tipo,clienteId:form.clienteId,origemSigla:data.agente.cidadeSigla,destinoSigla:form.destinoSigla,valorEstimado:form.valor?Number(form.valor):null,observacao:form.observacao||null,clientUuid:crypto.randomUUID()});setOpen(false);setForm({tipo:"carga",clienteId:"",destinoSigla:"",valor:"",observacao:""});setMessage("Captação registrada. Ela é um pedido comercial; não criou carga, viagem ou volume.");await load();}catch(e){setMessage(e instanceof Error?e.message:"Não foi possível registrar a captação.");}finally{setBusy(false);}}
  if(!data)return <section className="surface-card p-5"><p className="text-sm text-muted-foreground">{message??"Carregando carteira e captações…"}</p>{message&&<button onClick={()=>void load()} className="mt-3 rounded-lg px-3 py-2 text-sm ring-1 ring-[color:var(--hairline)]">Tentar novamente</button>}</section>;
  const kpis=[{label:"Minha carteira",value:String(data.resumo.clientes)},{label:"Cotações abertas",value:String(data.resumo.cotacoesAbertas)},{label:"Captado no mês",value:brl(data.resumo.captadoMes)},{label:"Comissão estimada",value:brl(data.resumo.comissaoEstimada)}];
  return <div className="space-y-5">
    <header className="flex items-start justify-between gap-3"><div><p className="champagne-eyebrow">Agência · {data.agente.cidadeSigla}</p><h1 className="mt-1 font-display text-3xl">Olá, {data.agente.nome}</h1><p className="mt-2 max-w-xl text-sm text-muted-foreground">Sua carteira, captações e pedidos comerciais. A comissão é uma estimativa; a apuração oficial é financeira.</p></div><button onClick={()=>void load()} aria-label="Atualizar" className="icon-button"><RefreshCw className="h-4 w-4"/></button></header>
    {message&&<p className="rounded-lg bg-[color:var(--muted)] p-3 text-sm">{message}</p>}
    <div className="grid grid-cols-2 gap-px overflow-hidden rounded-xl bg-[color:var(--hairline)] sm:grid-cols-4">{kpis.map(k=><div key={k.label} className="bg-[color:var(--card)] p-4"><p className="text-xs text-muted-foreground">{k.label}</p><strong className="mt-2 block font-mono text-lg leading-tight">{k.value}</strong></div>)}</div>
    <button onClick={()=>setOpen(v=>!v)} className="inline-flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-[color:var(--brand)] font-semibold text-white"><ClipboardPlus className="h-5 w-5"/>{open?"Fechar captação":"Registrar captação"}</button>
    {open&&<section className="surface-card grid gap-3 p-4 sm:grid-cols-2"><div className="sm:col-span-2"><h2 className="font-display text-xl">Novo pedido comercial</h2><p className="mt-1 text-xs text-muted-foreground">A origem é sua agência ({data.agente.cidadeSigla}) e não pode ser alterada. Cargas físicas só são montadas pelo TMS a partir de NF/DC.</p></div><label className="field-label">Tipo<select className="field mt-1" value={form.tipo} onChange={e=>setForm({...form,tipo:e.target.value as typeof form.tipo})}>{[["carga","Carga"],["encomenda","Encomenda"],["veiculo","Veículo"],["maquina","Máquina"]].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="field-label">Cliente da sua carteira<select className="field mt-1" value={form.clienteId} onChange={e=>setForm({...form,clienteId:e.target.value})}><option value="">Selecionar cliente</option>{clientes.map(c=><option key={c.id} value={c.id}>{c.codigo} · {c.nome}</option>)}</select></label><label className="field-label">Destino<select className="field mt-1" value={form.destinoSigla} onChange={e=>setForm({...form,destinoSigla:e.target.value})}><option value="">Selecionar destino</option>{destinos.map(c=><option key={c.sigla} value={c.sigla}>{c.nome} · {c.sigla}</option>)}</select></label><label className="field-label">Valor estimado (opcional)<input type="number" min="0" step="0.01" className="field mt-1" value={form.valor} onChange={e=>setForm({...form,valor:e.target.value})}/></label><label className="field-label sm:col-span-2">Observação<input className="field mt-1" value={form.observacao} onChange={e=>setForm({...form,observacao:e.target.value})}/></label><button disabled={busy||!form.clienteId||!form.destinoSigla} onClick={()=>void save()} className="h-12 rounded-xl bg-[color:var(--brand)] font-semibold text-white disabled:opacity-50 sm:col-span-2">{busy?"Registrando…":"Registrar pedido comercial"}</button></section>}
    <section className="surface-card p-4"><div className="flex items-center gap-2"><Users className="h-5 w-5 text-[color:var(--brand)]"/><h2 className="font-display text-xl">Minha carteira</h2></div><div className="mt-3 divide-y divide-[color:var(--hairline)]">{data.clientes.slice(0,8).map(c=><div key={c.id} className="flex items-center justify-between gap-3 py-3"><span><strong className="text-sm">{c.nome}</strong><small className="block font-mono text-xs text-muted-foreground">{c.codigo} · {c.cidade_sigla??"sem cidade"}</small></span><ChevronRight className="h-4 w-4 text-muted-foreground"/></div>)}{!data.clientes.length&&<p className="py-4 text-sm text-muted-foreground">Sua carteira ainda não possui clientes vinculados.</p>}</div></section>
    <section className="surface-card p-4"><div className="flex items-center gap-2"><BriefcaseBusiness className="h-5 w-5 text-[color:var(--brand)]"/><h2 className="font-display text-xl">Pedidos recentes</h2></div><div className="mt-3 space-y-2">{data.pedidos.slice(0,8).map(p=><div key={p.id} className="flex justify-between gap-3 rounded-lg bg-[color:var(--muted)] p-3"><span><strong className="font-mono text-xs">{p.codigo}</strong><small className="mt-1 block text-xs text-muted-foreground">{p.cliente_nome} · {p.origem_sigla} → {p.destino_sigla}</small></span><span className="text-right"><small className="block text-xs">{p.status.replaceAll("_"," ")}</small><strong className="font-mono text-xs">{brl(p.valor_estimado)}</strong></span></div>)}{!data.pedidos.length&&<p className="py-4 text-sm text-muted-foreground">Nenhum pedido comercial registrado.</p>}</div></section>
  </div>;
}
