import { useMemo, useState } from "react";
import { Check, Pencil, Plus, X } from "lucide-react";
import { createAgente, updateAgente, type AgenteApi, type CidadeApi, type UsuarioCadastroApi } from "@/lib/ajc-api";

export function AgentsRegistry({agents,setAgents,cidades,usuarios}:{agents:AgenteApi[];setAgents:(rows:AgenteApi[])=>void;cidades:CidadeApi[];usuarios:UsuarioCadastroApi[]}){
  const [editing,setEditing]=useState<string|null>(null); const [open,setOpen]=useState(false); const [error,setError]=useState<string|null>(null);
  const blank={nome:"",cidadeSigla:"",percentualComissao:"",usuarioId:"",ativo:true}; const [form,setForm]=useState(blank);
  const cidadeNome=useMemo(()=>Object.fromEntries(cidades.map(c=>[c.sigla,c.nome])),[cidades]);
  function edit(row:AgenteApi){setForm({nome:row.nome,cidadeSigla:row.cidadeSigla,percentualComissao:row.percentualComissao==null?"":String(row.percentualComissao),usuarioId:row.usuarioId??"",ativo:row.ativo});setEditing(row.id);setOpen(true);setError(null);}
  async function save(){if(!form.nome.trim()||!form.cidadeSigla)return setError("Nome e cidade são obrigatórios.");try{const input={nome:form.nome,cidadeSigla:form.cidadeSigla,percentualComissao:form.percentualComissao?Number(form.percentualComissao):null,usuarioId:form.usuarioId||null,ativo:form.ativo};const saved=editing?await updateAgente(editing,input):await createAgente(input);setAgents([saved,...agents.filter(a=>a.id!==saved.id)]);setOpen(false);setEditing(null);setForm(blank);setError(null);}catch(e){setError(e instanceof Error?e.message:"Não foi possível salvar o agente.");}}
  return <section className="space-y-4"><div className="flex items-start justify-between gap-3"><div><h2 className="font-display text-2xl">Agentes comerciais</h2><p className="mt-1 max-w-xl text-sm text-muted-foreground">Cadastre a cidade, a conta que acessará o app e a comissão de referência. O agente só enxerga sua própria carteira.</p></div><button onClick={()=>{setForm(blank);setEditing(null);setOpen(true)}} className="inline-flex h-10 items-center gap-2 rounded-lg bg-[color:var(--brand)] px-3 text-sm font-semibold text-white"><Plus className="h-4 w-4"/>Novo agente</button></div>{open&&<div className="surface-card grid gap-3 p-4 sm:grid-cols-2"><label className="field-label">Nome<input className="field mt-1" value={form.nome} onChange={e=>setForm({...form,nome:e.target.value})}/></label><label className="field-label">Cidade<select className="field mt-1" value={form.cidadeSigla} onChange={e=>setForm({...form,cidadeSigla:e.target.value})}><option value="">Selecionar cidade</option>{cidades.filter(c=>c.ativo).map(c=><option key={c.sigla} value={c.sigla}>{c.nome} · {c.sigla}</option>)}</select></label><label className="field-label">Usuário de login<select className="field mt-1" value={form.usuarioId} onChange={e=>setForm({...form,usuarioId:e.target.value})}><option value="">Sem vínculo ainda</option>{usuarios.filter(u=>u.ativo).map(u=><option key={u.id} value={u.id}>{u.nome} · {u.login}</option>)}</select></label><label className="field-label">Comissão de referência (%)<input type="number" min="0" max="100" step="0.01" className="field mt-1" value={form.percentualComissao} onChange={e=>setForm({...form,percentualComissao:e.target.value})}/></label>{error&&<p className="rounded-lg bg-[color:var(--muted)] p-3 text-sm sm:col-span-2">{error}</p>}<div className="flex justify-end gap-2 sm:col-span-2"><button onClick={()=>setOpen(false)} className="h-10 rounded-lg px-3 text-sm ring-1 ring-[color:var(--hairline)]">Cancelar</button><button onClick={()=>void save()} className="inline-flex h-10 items-center gap-2 rounded-lg bg-[color:var(--brand)] px-4 text-sm font-semibold text-white"><Check className="h-4 w-4"/>Salvar agente</button></div></div>}
  <div className="space-y-2">{agents.map(row=><div key={row.id} className="surface-card flex items-center justify-between gap-3 p-4"><span><strong>{row.nome}</strong><small className="mt-1 block text-xs text-muted-foreground">{cidadeNome[row.cidadeSigla]??row.cidadeSigla} · {row.usuarioNome?`login: ${row.usuarioNome}`:"sem login vinculado"} · {row.percentualComissao==null?"comissão não publicada":`${row.percentualComissao}% de referência`}</small></span><button onClick={()=>edit(row)} aria-label={`Editar ${row.nome}`} className="icon-button"><Pencil className="h-4 w-4"/></button></div>)}{!agents.length&&<div className="surface-card p-6 text-sm text-muted-foreground">Nenhum agente cadastrado.</div>}</div></section>;
}
