import { useEffect, useState } from "react";
import { Check, Plus } from "lucide-react";
import { GhostButton, PrimaryButton, StatusChip } from "@/components/ops/primitives";
import { getConfigValue, listFinanceiroCentrosCusto, listFinanceiroPlanoContas, publishConfigValue, saveFinanceiroCentroCusto, saveFinanceiroPlanoConta, type ConfigValueApi, type FinanceiroCentroCustoApi, type FinanceiroPlanoContaApi } from "@/lib/ajc-api";

type FinanceiroRules = {
  schemaVersion: number;
  comissoes: { base: "recebido"; status: string[]; permitirRepasseManual: boolean };
  dre: { modo: "caixa" | "competencia"; periodicidade: "mensal" };
  faturas: { rastreamento: "interno" | "integracao"; provedor: string | null };
  categorias: Array<{ codigo: string; nome: string; tipo: "receita" | "despesa"; ativo: boolean }>;
};

const emptyRules: FinanceiroRules = { schemaVersion: 1, comissoes: { base: "recebido", status: ["em_aberto", "liberada", "pago"], permitirRepasseManual: true }, dre: { modo: "caixa", periodicidade: "mensal" }, faturas: { rastreamento: "interno", provedor: null }, categorias: [] };

export function OperationalFinanceConfig() {
  const [published, setPublished] = useState<ConfigValueApi | null>(null);
  const [draft, setDraft] = useState<FinanceiroRules>(emptyRules);
  const [planos, setPlanos] = useState<FinanceiroPlanoContaApi[]>([]);
  const [centros, setCentros] = useState<FinanceiroCentroCustoApi[]>([]);
  const [novoPlano, setNovoPlano] = useState({ codigo: "", nome: "", natureza: "receita" as FinanceiroPlanoContaApi["natureza"] });
  const [novoCentro, setNovoCentro] = useState({ codigo: "", nome: "" });
  const [novaCategoria, setNovaCategoria] = useState({ codigo: "", nome: "", tipo: "receita" as "receita" | "despesa" });
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState("");

  useEffect(() => { Promise.all([getConfigValue("financeiro_operacao"), listFinanceiroPlanoContas(), listFinanceiroCentrosCusto()]).then(([config, plano, centro]) => { setPublished(config); setDraft(structuredClone(config.valor as FinanceiroRules)); setPlanos(plano); setCentros(centro); }).catch((error) => setMessage(error instanceof Error ? error.message : "Falha ao carregar configuracao financeira")); }, []);
  const dirty = JSON.stringify(published?.valor) !== JSON.stringify(draft);

  async function publicar() { setBusy(true); setMessage(""); try { const saved = await publishConfigValue("financeiro_operacao", draft); setPublished(saved); setDraft(structuredClone(saved.valor as FinanceiroRules)); setMessage(`Regras financeiras publicadas na versao ${saved.versao}.`); } catch (error) { setMessage(error instanceof Error ? error.message : "Falha ao publicar regras"); } finally { setBusy(false); } }
  async function adicionarPlano() { if (!novoPlano.codigo.trim() || !novoPlano.nome.trim()) return; setBusy(true); try { const saved = await saveFinanceiroPlanoConta(novoPlano); setPlanos((items) => [...items.filter((item) => item.id !== saved.id), saved].sort((a, b) => a.codigo.localeCompare(b.codigo))); setNovoPlano({ codigo: "", nome: "", natureza: "receita" }); } catch (error) { setMessage(error instanceof Error ? error.message : "Falha ao salvar plano de contas"); } finally { setBusy(false); } }
  async function adicionarCentro() { if (!novoCentro.codigo.trim() || !novoCentro.nome.trim()) return; setBusy(true); try { const saved = await saveFinanceiroCentroCusto(novoCentro); setCentros((items) => [...items.filter((item) => item.id !== saved.id), saved].sort((a, b) => a.codigo.localeCompare(b.codigo))); setNovoCentro({ codigo: "", nome: "" }); } catch (error) { setMessage(error instanceof Error ? error.message : "Falha ao salvar centro de custo"); } finally { setBusy(false); } }
  function adicionarCategoria() { if (!novaCategoria.codigo.trim() || !novaCategoria.nome.trim()) return; setDraft((current) => ({ ...current, categorias: [...current.categorias, { ...novaCategoria, ativo: true }] })); setNovaCategoria({ codigo: "", nome: "", tipo: "receita" }); }

  return <section className="surface-card mt-4 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[10px] font-semibold uppercase tracking-[0.14em] text-muted-foreground">Financeiro</p><h2 className="mt-1 font-display text-xl">Configuração contábil e financeira</h2><p className="mt-1 max-w-2xl text-sm text-muted-foreground">Cadastre a estrutura que alimenta AP, AR, comissões e DRE. Publicar cria uma versão auditável; o sistema não inventa conta, centro ou percentual.</p></div><PrimaryButton icon={Check} disabled={busy || !dirty} onClick={() => void publicar()}>{busy ? "Salvando..." : "Publicar regras"}</PrimaryButton></div>
    {message && <p className="mt-3 rounded-md bg-[color:var(--muted)] px-3 py-2 text-xs text-muted-foreground">{message}</p>}
    <div className="mt-5 grid gap-4 xl:grid-cols-3"><div className="rounded-lg bg-[color:var(--muted)] p-4 ring-1 ring-[color:var(--hairline)]"><h3 className="text-sm font-semibold">Comissões</h3><p className="mt-1 text-xs text-muted-foreground">A liberação depende sempre do recebimento efetivo.</p><label className="mt-3 flex items-center justify-between text-xs"><span>Permitir repasse manual</span><input type="checkbox" checked={draft.comissoes.permitirRepasseManual} onChange={(e) => setDraft((current) => ({ ...current, comissoes: { ...current.comissoes, permitirRepasseManual: e.target.checked } }))} /></label><div className="mt-3 flex flex-wrap gap-1">{draft.comissoes.status.map((status) => <StatusChip key={status} tone={status === "pago" ? "success" : status === "liberada" ? "warning" : "info"}>{status}</StatusChip>)}</div></div><div className="rounded-lg bg-[color:var(--muted)] p-4 ring-1 ring-[color:var(--hairline)]"><h3 className="text-sm font-semibold">DRE</h3><label className="mt-3 block text-xs text-muted-foreground">Modo<select value={draft.dre.modo} onChange={(e) => setDraft((current) => ({ ...current, dre: { ...current.dre, modo: e.target.value as "caixa" | "competencia" } }))} className="field mt-1"><option value="caixa">Caixa (liquidado)</option><option value="competencia">Competência</option></select></label></div><div className="rounded-lg bg-[color:var(--muted)] p-4 ring-1 ring-[color:var(--hairline)]"><h3 className="text-sm font-semibold">Faturas</h3><label className="mt-3 block text-xs text-muted-foreground">Rastreamento<select value={draft.faturas.rastreamento} onChange={(e) => setDraft((current) => ({ ...current, faturas: { ...current.faturas, rastreamento: e.target.value as "interno" | "integracao" } }))} className="field mt-1"><option value="interno">Controle interno</option><option value="integracao">Provedor externo</option></select></label>{draft.faturas.rastreamento === "integracao" && <input value={draft.faturas.provedor ?? ""} onChange={(e) => setDraft((current) => ({ ...current, faturas: { ...current.faturas, provedor: e.target.value } }))} placeholder="Nome do provedor contratado" className="field mt-3" />}</div></div>
    <div className="mt-5 grid gap-4 lg:grid-cols-3"><Registry title="Plano de contas" fields={["Código", "Nome"]} values={novoPlano} onChange={(key, value) => setNovoPlano((current) => ({ ...current, [key]: value }))} onAdd={adicionarPlano} rows={planos.map((item) => `${item.codigo} · ${item.nome} · ${item.natureza}`)} select={<select value={novoPlano.natureza} onChange={(e) => setNovoPlano((current) => ({ ...current, natureza: e.target.value as FinanceiroPlanoContaApi["natureza"] }))} className="field"><option value="receita">Receita</option><option value="despesa">Despesa</option><option value="ativo">Ativo</option><option value="passivo">Passivo</option><option value="patrimonio">Patrimônio</option></select>} /><Registry title="Centros de custo" fields={["Código", "Nome"]} values={novoCentro} onChange={(key, value) => setNovoCentro((current) => ({ ...current, [key]: value }))} onAdd={adicionarCentro} rows={centros.map((item) => `${item.codigo} · ${item.nome}`)} /><Registry title="Categorias gerenciais" fields={["Código", "Nome"]} values={novaCategoria} onChange={(key, value) => setNovaCategoria((current) => ({ ...current, [key]: value }))} onAdd={adicionarCategoria} rows={draft.categorias.map((item) => `${item.codigo} · ${item.nome} · ${item.tipo}`)} select={<select value={novaCategoria.tipo} onChange={(e) => setNovaCategoria((current) => ({ ...current, tipo: e.target.value as "receita" | "despesa" }))} className="field"><option value="receita">Receita</option><option value="despesa">Despesa</option></select>} /></div>
  </section>;
}

function Registry({ title, fields, values, onChange, onAdd, rows, select }: { title: string; fields: string[]; values: Record<string, string>; onChange: (key: string, value: string) => void; onAdd: () => void; rows: string[]; select?: React.ReactNode }) { const keys = ["codigo", "nome"]; return <div className="rounded-lg bg-[color:var(--muted)] p-4 ring-1 ring-[color:var(--hairline)]"><h3 className="text-sm font-semibold">{title}</h3><div className="mt-3 grid gap-2">{fields.map((label, index) => <input key={label} aria-label={label} placeholder={label} value={values[keys[index]] ?? ""} onChange={(e) => onChange(keys[index], e.target.value)} className="field" />)}{select}<GhostButton icon={Plus} onClick={onAdd}>Adicionar</GhostButton></div><div className="mt-3 max-h-40 space-y-1 overflow-auto">{rows.length ? rows.map((row) => <p key={row} className="rounded-md bg-[color:var(--surface-elev)] px-2.5 py-2 text-xs text-muted-foreground">{row}</p>) : <p className="text-xs text-muted-foreground">Nenhum registro cadastrado.</p>}</div></div>; }
