import { useEffect, useState } from "react";
import { Plus, Save, Trash2, WalletCards } from "lucide-react";
import { PrimaryButton, StatusChip } from "@/components/ops/primitives";
import { getConfigValue, publishConfigValue, type CidadeApi, type ConfigValueApi, type PrestacaoConfigApi } from "@/lib/ajc-api";

type Rules=PrestacaoConfigApi["valor"];type CatalogKey="formasPagamento"|"categoriasReceita"|"categoriasDespesa";
export function OperationalPrestacaoConfig({cidades}:{cidades:CidadeApi[]}){const [published,setPublished]=useState<ConfigValueApi|null>(null);const [draft,setDraft]=useState<Rules|null>(null);const [saving,setSaving]=useState(false);const [message,setMessage]=useState("");useEffect(()=>{getConfigValue("tms_prestacao_contas").then(v=>{setPublished(v);setDraft(v.valor as Rules)}).catch(e=>setMessage(e instanceof Error?e.message:"Falha ao carregar regras"));},[]);if(!draft)return <section className="surface-card p-5 text-sm text-muted-foreground">{message||"Carregando regras da prestação..."}</section>;const dirty=JSON.stringify(published?.valor)!==JSON.stringify(draft);
  function addCatalog(key:CatalogKey){setDraft({...draft,[key]:[...draft[key],{codigo:`novo_${draft[key].length+1}`,nome:"Nova opção",ativo:true}]});}function updateCatalog(key:CatalogKey,index:number,patch:Record<string,unknown>){setDraft({...draft,[key]:draft[key].map((x,i)=>i===index?{...x,...patch}:x)});}
  async function publish(){setSaving(true);setMessage("");try{const saved=await publishConfigValue("tms_prestacao_contas",draft);setPublished(saved);setDraft(saved.valor as Rules);setMessage(`Versão ${saved.versao} publicada.`);}catch(e){setMessage(e instanceof Error?e.message:"Falha ao publicar");}finally{setSaving(false);}}
  return <section className="surface-card p-5"><header className="flex flex-wrap items-start justify-between gap-3 border-b border-[color:var(--hairline)] pb-4"><div><div className="flex items-center gap-2"><WalletCards className="h-4 w-4 text-[color:var(--brand)]"/><h3 className="font-display text-xl">Prestação de contas</h3></div><p className="mt-1 max-w-3xl text-xs text-muted-foreground">Formas de pagamento, categorias, intertrechos e comissões usados pelo app do gerente e pelo TMS.</p></div><div className="flex gap-2"><StatusChip tone="neutral">versão {published?.versao??"—"}</StatusChip>{dirty&&<StatusChip tone="warning">não publicada</StatusChip>}</div></header>
    <div className="mt-5 grid gap-4 xl:grid-cols-3"><Catalog title="Formas de pagamento" items={draft.formasPagamento} onAdd={()=>addCatalog("formasPagamento")} onUpdate={(i,p)=>updateCatalog("formasPagamento",i,p)}/><Catalog title="Categorias de receita" items={draft.categoriasReceita} onAdd={()=>addCatalog("categoriasReceita")} onUpdate={(i,p)=>updateCatalog("categoriasReceita",i,p)}/><Catalog title="Categorias de despesa" items={draft.categoriasDespesa} onAdd={()=>addCatalog("categoriasDespesa")} onUpdate={(i,p)=>updateCatalog("categoriasDespesa",i,p)}/></div>
    <div className="mt-4 grid gap-4 xl:grid-cols-2"><Box title="Intertrechos permitidos"><div className="space-y-2">{draft.intertrechos.map((x,i)=><div key={i} className="grid grid-cols-[1fr_1fr_auto] gap-2"><select className="field" value={x.origemSigla} onChange={e=>setDraft({...draft,intertrechos:draft.intertrechos.map((v,j)=>j===i?{...v,origemSigla:e.target.value}:v)})}>{cidades.map(c=><option key={c.sigla} value={c.sigla}>{c.nome}</option>)}</select><select className="field" value={x.destinoSigla} onChange={e=>setDraft({...draft,intertrechos:draft.intertrechos.map((v,j)=>j===i?{...v,destinoSigla:e.target.value}:v)})}>{cidades.map(c=><option key={c.sigla} value={c.sigla}>{c.nome}</option>)}</select><button aria-label="Remover" onClick={()=>setDraft({...draft,intertrechos:draft.intertrechos.filter((_,j)=>j!==i)})}><Trash2 className="h-4 w-4"/></button></div>)}</div><button className="mt-3 inline-flex items-center gap-2 text-xs" onClick={()=>setDraft({...draft,intertrechos:[...draft.intertrechos,{origemSigla:cidades[0]?.sigla??"",destinoSigla:cidades[1]?.sigla??cidades[0]?.sigla??"",ativo:true}]})}><Plus className="h-4 w-4"/>Adicionar intertrecho</button></Box>
      <Box title="Comissões de agência"><div className="space-y-2">{draft.comissoesAgencia.map((x,i)=><div key={i} className="grid grid-cols-[1fr_7rem_auto] gap-2"><input className="field" placeholder="Agência" value={x.agenciaNome} onChange={e=>setDraft({...draft,comissoesAgencia:draft.comissoesAgencia.map((v,j)=>j===i?{...v,agenciaNome:e.target.value}:v)})}/><input className="field" type="number" min="0" max="100" step="0.01" value={x.percentual} onChange={e=>setDraft({...draft,comissoesAgencia:draft.comissoesAgencia.map((v,j)=>j===i?{...v,percentual:Number(e.target.value)}:v)})}/><button aria-label="Remover" onClick={()=>setDraft({...draft,comissoesAgencia:draft.comissoesAgencia.filter((_,j)=>j!==i)})}><Trash2 className="h-4 w-4"/></button></div>)}</div><button className="mt-3 inline-flex items-center gap-2 text-xs" onClick={()=>setDraft({...draft,comissoesAgencia:[...draft.comissoesAgencia,{agenciaNome:"",percentual:0,ativo:true}]})}><Plus className="h-4 w-4"/>Adicionar comissão</button></Box></div>
    <footer className="mt-5 flex flex-wrap items-center justify-between gap-3 border-t border-[color:var(--hairline)] pt-4"><p className="text-xs text-muted-foreground">Valores operacionais só entram após publicação auditável.</p><PrimaryButton icon={Save} disabled={!dirty||saving} onClick={publish}>{saving?"Publicando...":"Publicar configuração"}</PrimaryButton></footer>{message&&<p className="mt-3 text-xs text-muted-foreground">{message}</p>}</section>;
}
function Catalog({title,items,onAdd,onUpdate}:{title:string;items:Array<{codigo:string;nome:string;ativo:boolean}>;onAdd:()=>void;onUpdate:(index:number,patch:Record<string,unknown>)=>void}){return <Box title={title}><div className="space-y-2">{items.map((x,i)=><div key={i} className="grid grid-cols-[1fr_1.2fr_auto] gap-2"><input className="field font-mono text-xs" value={x.codigo} onChange={e=>onUpdate(i,{codigo:e.target.value})}/><input className="field" value={x.nome} onChange={e=>onUpdate(i,{nome:e.target.value})}/><input type="checkbox" checked={x.ativo} onChange={e=>onUpdate(i,{ativo:e.target.checked})}/></div>)}</div><button className="mt-3 inline-flex items-center gap-2 text-xs" onClick={onAdd}><Plus className="h-4 w-4"/>Adicionar opção</button></Box>}
function Box({title,children}:{title:string;children:React.ReactNode}){return <div className="rounded-xl bg-[color:var(--surface-tint)] p-4 ring-1 ring-[color:var(--hairline)]"><h4 className="mb-3 text-sm font-semibold">{title}</h4>{children}</div>}
