/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TotemRouteImport } from './routes/totem'
import { Route as PosRouteImport } from './routes/pos'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as EmbarqueRouteImport } from './routes/embarque'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ClienteRouteImport } from './routes/cliente'
import { Route as CampoRouteImport } from './routes/campo'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampoIndexRouteImport } from './routes/campo.index'
import { Route as CampoRecebimentoRouteImport } from './routes/campo.recebimento'
import { Route as CampoPortariaRouteImport } from './routes/campo.portaria'
import { Route as CampoEntregasRouteImport } from './routes/campo.entregas'
import { Route as CampoConferenciaRouteImport } from './routes/campo.conferencia'
import { Route as AppVendasRouteImport } from './routes/app.vendas'
import { Route as AppTmsRouteImport } from './routes/app.tms'
import { Route as AppNavegacaoRouteImport } from './routes/app.navegacao'
import { Route as AppInicioRouteImport } from './routes/app.inicio'
import { Route as AppFinanceiroRouteImport } from './routes/app.financeiro'
import { Route as AppEncomendasRouteImport } from './routes/app.encomendas'
import { Route as AppCrmRouteImport } from './routes/app.crm'
import { Route as AppCadastrosRouteImport } from './routes/app.cadastros'

const TotemRoute = TotemRouteImport.update({
  id: '/totem',
  path: '/totem',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbarqueRoute = EmbarqueRouteImport.update({
  id: '/embarque',
  path: '/embarque',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteRoute = ClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const CampoRoute = CampoRouteImport.update({
  id: '/campo',
  path: '/campo',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampoIndexRoute = CampoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CampoRoute,
} as any)
const CampoRecebimentoRoute = CampoRecebimentoRouteImport.update({
  id: '/recebimento',
  path: '/recebimento',
  getParentRoute: () => CampoRoute,
} as any)
const CampoPortariaRoute = CampoPortariaRouteImport.update({
  id: '/portaria',
  path: '/portaria',
  getParentRoute: () => CampoRoute,
} as any)
const CampoEntregasRoute = CampoEntregasRouteImport.update({
  id: '/entregas',
  path: '/entregas',
  getParentRoute: () => CampoRoute,
} as any)
const CampoConferenciaRoute = CampoConferenciaRouteImport.update({
  id: '/conferencia',
  path: '/conferencia',
  getParentRoute: () => CampoRoute,
} as any)
const AppVendasRoute = AppVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => AppRoute,
} as any)
const AppTmsRoute = AppTmsRouteImport.update({
  id: '/tms',
  path: '/tms',
  getParentRoute: () => AppRoute,
} as any)
const AppNavegacaoRoute = AppNavegacaoRouteImport.update({
  id: '/navegacao',
  path: '/navegacao',
  getParentRoute: () => AppRoute,
} as any)
const AppInicioRoute = AppInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppEncomendasRoute = AppEncomendasRouteImport.update({
  id: '/encomendas',
  path: '/encomendas',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmRoute = AppCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AppRoute,
} as any)
const AppCadastrosRoute = AppCadastrosRouteImport.update({
  id: '/cadastros',
  path: '/cadastros',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/campo': typeof CampoRouteWithChildren
  '/cliente': typeof ClienteRoute
  '/dashboard': typeof DashboardRoute
  '/embarque': typeof EmbarqueRoute
  '/portal': typeof PortalRoute
  '/pos': typeof PosRoute
  '/totem': typeof TotemRoute
  '/app/cadastros': typeof AppCadastrosRoute
  '/app/crm': typeof AppCrmRoute
  '/app/encomendas': typeof AppEncomendasRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/inicio': typeof AppInicioRoute
  '/app/navegacao': typeof AppNavegacaoRoute
  '/app/tms': typeof AppTmsRoute
  '/app/vendas': typeof AppVendasRoute
  '/campo/conferencia': typeof CampoConferenciaRoute
  '/campo/entregas': typeof CampoEntregasRoute
  '/campo/portaria': typeof CampoPortariaRoute
  '/campo/recebimento': typeof CampoRecebimentoRoute
  '/campo/': typeof CampoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/cliente': typeof ClienteRoute
  '/dashboard': typeof DashboardRoute
  '/embarque': typeof EmbarqueRoute
  '/portal': typeof PortalRoute
  '/pos': typeof PosRoute
  '/totem': typeof TotemRoute
  '/app/cadastros': typeof AppCadastrosRoute
  '/app/crm': typeof AppCrmRoute
  '/app/encomendas': typeof AppEncomendasRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/inicio': typeof AppInicioRoute
  '/app/navegacao': typeof AppNavegacaoRoute
  '/app/tms': typeof AppTmsRoute
  '/app/vendas': typeof AppVendasRoute
  '/campo/conferencia': typeof CampoConferenciaRoute
  '/campo/entregas': typeof CampoEntregasRoute
  '/campo/portaria': typeof CampoPortariaRoute
  '/campo/recebimento': typeof CampoRecebimentoRoute
  '/campo': typeof CampoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/campo': typeof CampoRouteWithChildren
  '/cliente': typeof ClienteRoute
  '/dashboard': typeof DashboardRoute
  '/embarque': typeof EmbarqueRoute
  '/portal': typeof PortalRoute
  '/pos': typeof PosRoute
  '/totem': typeof TotemRoute
  '/app/cadastros': typeof AppCadastrosRoute
  '/app/crm': typeof AppCrmRoute
  '/app/encomendas': typeof AppEncomendasRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/inicio': typeof AppInicioRoute
  '/app/navegacao': typeof AppNavegacaoRoute
  '/app/tms': typeof AppTmsRoute
  '/app/vendas': typeof AppVendasRoute
  '/campo/conferencia': typeof CampoConferenciaRoute
  '/campo/entregas': typeof CampoEntregasRoute
  '/campo/portaria': typeof CampoPortariaRoute
  '/campo/recebimento': typeof CampoRecebimentoRoute
  '/campo/': typeof CampoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/campo'
    | '/cliente'
    | '/dashboard'
    | '/embarque'
    | '/portal'
    | '/pos'
    | '/totem'
    | '/app/cadastros'
    | '/app/crm'
    | '/app/encomendas'
    | '/app/financeiro'
    | '/app/inicio'
    | '/app/navegacao'
    | '/app/tms'
    | '/app/vendas'
    | '/campo/conferencia'
    | '/campo/entregas'
    | '/campo/portaria'
    | '/campo/recebimento'
    | '/campo/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/cliente'
    | '/dashboard'
    | '/embarque'
    | '/portal'
    | '/pos'
    | '/totem'
    | '/app/cadastros'
    | '/app/crm'
    | '/app/encomendas'
    | '/app/financeiro'
    | '/app/inicio'
    | '/app/navegacao'
    | '/app/tms'
    | '/app/vendas'
    | '/campo/conferencia'
    | '/campo/entregas'
    | '/campo/portaria'
    | '/campo/recebimento'
    | '/campo'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/campo'
    | '/cliente'
    | '/dashboard'
    | '/embarque'
    | '/portal'
    | '/pos'
    | '/totem'
    | '/app/cadastros'
    | '/app/crm'
    | '/app/encomendas'
    | '/app/financeiro'
    | '/app/inicio'
    | '/app/navegacao'
    | '/app/tms'
    | '/app/vendas'
    | '/campo/conferencia'
    | '/campo/entregas'
    | '/campo/portaria'
    | '/campo/recebimento'
    | '/campo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CampoRoute: typeof CampoRouteWithChildren
  ClienteRoute: typeof ClienteRoute
  DashboardRoute: typeof DashboardRoute
  EmbarqueRoute: typeof EmbarqueRoute
  PortalRoute: typeof PortalRoute
  PosRoute: typeof PosRoute
  TotemRoute: typeof TotemRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/totem': {
      id: '/totem'
      path: '/totem'
      fullPath: '/totem'
      preLoaderRoute: typeof TotemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embarque': {
      id: '/embarque'
      path: '/embarque'
      fullPath: '/embarque'
      preLoaderRoute: typeof EmbarqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente': {
      id: '/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof ClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campo': {
      id: '/campo'
      path: '/campo'
      fullPath: '/campo'
      preLoaderRoute: typeof CampoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campo/': {
      id: '/campo/'
      path: '/'
      fullPath: '/campo/'
      preLoaderRoute: typeof CampoIndexRouteImport
      parentRoute: typeof CampoRoute
    }
    '/campo/recebimento': {
      id: '/campo/recebimento'
      path: '/recebimento'
      fullPath: '/campo/recebimento'
      preLoaderRoute: typeof CampoRecebimentoRouteImport
      parentRoute: typeof CampoRoute
    }
    '/campo/portaria': {
      id: '/campo/portaria'
      path: '/portaria'
      fullPath: '/campo/portaria'
      preLoaderRoute: typeof CampoPortariaRouteImport
      parentRoute: typeof CampoRoute
    }
    '/campo/entregas': {
      id: '/campo/entregas'
      path: '/entregas'
      fullPath: '/campo/entregas'
      preLoaderRoute: typeof CampoEntregasRouteImport
      parentRoute: typeof CampoRoute
    }
    '/campo/conferencia': {
      id: '/campo/conferencia'
      path: '/conferencia'
      fullPath: '/campo/conferencia'
      preLoaderRoute: typeof CampoConferenciaRouteImport
      parentRoute: typeof CampoRoute
    }
    '/app/vendas': {
      id: '/app/vendas'
      path: '/vendas'
      fullPath: '/app/vendas'
      preLoaderRoute: typeof AppVendasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tms': {
      id: '/app/tms'
      path: '/tms'
      fullPath: '/app/tms'
      preLoaderRoute: typeof AppTmsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/navegacao': {
      id: '/app/navegacao'
      path: '/navegacao'
      fullPath: '/app/navegacao'
      preLoaderRoute: typeof AppNavegacaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inicio': {
      id: '/app/inicio'
      path: '/inicio'
      fullPath: '/app/inicio'
      preLoaderRoute: typeof AppInicioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/financeiro': {
      id: '/app/financeiro'
      path: '/financeiro'
      fullPath: '/app/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/encomendas': {
      id: '/app/encomendas'
      path: '/encomendas'
      fullPath: '/app/encomendas'
      preLoaderRoute: typeof AppEncomendasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/crm': {
      id: '/app/crm'
      path: '/crm'
      fullPath: '/app/crm'
      preLoaderRoute: typeof AppCrmRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cadastros': {
      id: '/app/cadastros'
      path: '/cadastros'
      fullPath: '/app/cadastros'
      preLoaderRoute: typeof AppCadastrosRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCadastrosRoute: typeof AppCadastrosRoute
  AppCrmRoute: typeof AppCrmRoute
  AppEncomendasRoute: typeof AppEncomendasRoute
  AppFinanceiroRoute: typeof AppFinanceiroRoute
  AppInicioRoute: typeof AppInicioRoute
  AppNavegacaoRoute: typeof AppNavegacaoRoute
  AppTmsRoute: typeof AppTmsRoute
  AppVendasRoute: typeof AppVendasRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCadastrosRoute: AppCadastrosRoute,
  AppCrmRoute: AppCrmRoute,
  AppEncomendasRoute: AppEncomendasRoute,
  AppFinanceiroRoute: AppFinanceiroRoute,
  AppInicioRoute: AppInicioRoute,
  AppNavegacaoRoute: AppNavegacaoRoute,
  AppTmsRoute: AppTmsRoute,
  AppVendasRoute: AppVendasRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface CampoRouteChildren {
  CampoConferenciaRoute: typeof CampoConferenciaRoute
  CampoEntregasRoute: typeof CampoEntregasRoute
  CampoPortariaRoute: typeof CampoPortariaRoute
  CampoRecebimentoRoute: typeof CampoRecebimentoRoute
  CampoIndexRoute: typeof CampoIndexRoute
}

const CampoRouteChildren: CampoRouteChildren = {
  CampoConferenciaRoute: CampoConferenciaRoute,
  CampoEntregasRoute: CampoEntregasRoute,
  CampoPortariaRoute: CampoPortariaRoute,
  CampoRecebimentoRoute: CampoRecebimentoRoute,
  CampoIndexRoute: CampoIndexRoute,
}

const CampoRouteWithChildren = CampoRoute._addFileChildren(CampoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CampoRoute: CampoRouteWithChildren,
  ClienteRoute: ClienteRoute,
  DashboardRoute: DashboardRoute,
  EmbarqueRoute: EmbarqueRoute,
  PortalRoute: PortalRoute,
  PosRoute: PosRoute,
  TotemRoute: TotemRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
