import { useEffect, useMemo, useState } from "react";
import { Camera, CheckCircle2, DoorOpen, LogOut, RefreshCw, Search, Truck, X } from "lucide-react";
import { AjcApiError, createCampoPortaria, exitCampoPortaria, getCampoPortariaConfig, listCampoEmpresas, listCampoPortaria, listTmsLocaisOperacionais, uploadCampoPortaria, type CampoEmpresaApi, type CampoPortariaApi, type TmsLocalOperacionalApi } from "@/lib/ajc-api";

type Mode = "patio" | "entrada" | "saida";

export function PortariaTab() {
  const [mode,setMode]=useState<Mode>("patio");
  const [rows,setRows]=useState<CampoPortariaApi[]>([]);
  const [locals,setLocals]=useState<TmsLocalOperacionalApi[]>([]);
  const [companies,setCompanies]=useState<CampoEmpresaApi[]>([]);
  const [config,setConfig]=useState<{fotoEntrada:string;fotoSaida:string;pollingSegundos:number}>({fotoEntrada:"opcional",fotoSaida:"opcional",pollingSegundos:20});
  const [query,setQuery]=useState(""); const [plate,setPlate]=useState(""); const [company,setCompany]=useState(""); const [companyId,setCompanyId]=useState(""); const [companyType,setCompanyType]=useState<"cliente"|"fornecedor">("cliente"); const [driver,setDriver]=useState(""); const [localId,setLocalId]=useState(""); const [photo,setPhoto]=useState<File|null>(null); const [selected,setSelected]=useState<CampoPortariaApi|null>(null); const [busy,setBusy]=useState(false); const [message,setMessage]=useState<string|null>(null);
  const patio=useMemo(()=>rows.filter(x=>!x.saida_em),[rows]);
  async function load(){setMessage(null);try{const [data,loc,cfg]=await Promise.all([listCampoPortaria({busca:query,situacao:"todas",porPagina:"100"}),listTmsLocaisOperacionais(),getCampoPortariaConfig()]);setRows(data.items);setLocals(loc.filter(x=>x.tipo==="porto"||x.tipo==="patio"));setConfig(cfg.valor);}catch(e){setMessage(e instanceof Error?e.message:"Falha ao carregar a portaria");}}
  useEffect(()=>{void load();},[]);
  useEffect(()=>{const t=window.setInterval(()=>void load(),Math.max(10,config.pollingSegundos)*1000);return()=>window.clearInterval(t);},[config.pollingSegundos,query]);
  async function searchCompany(value:string){setCompany(value);setCompanyId("");if(value.trim().length>=2){try{setCompanies(await listCampoEmpresas(value));}catch{setCompanies([]);}}else setCompanies([]);}
  async function submit(){if(!plate||!company||!localId)return setMessage("Placa, empresa e local operacional são obrigatórios.");setBusy(true);setMessage(null);try{let evidence:{url:string;hash:string}|undefined;if(photo)evidence=await uploadCampoPortaria(photo);await createCampoPortaria({placa:plate,empresaNome:company,empresaId:companyId||undefined,empresaTipo:companyId?companyType:undefined,motoristaNome:driver,localOperacionalId:localId,fotoUrl:evidence?.url,fotoHash:evidence?.hash,clientUuid:crypto.randomUUID()});setMode("patio");setPlate("");setCompany("");setDriver("");setPhoto(null);await load();setMessage("Entrada registrada e auditada.");}catch(e){setMessage(e instanceof AjcApiError?e.message:"Não foi possível registrar a entrada.");}finally{setBusy(false);}}
  async function submitExit(){if(!selected)return;setBusy(true);setMessage(null);try{await exitCampoPortaria(selected.id,{clientUuid:crypto.randomUUID()});setSelected(null);setMode("patio");await load();setMessage("Saída registrada e auditada.");}catch(e){setMessage(e instanceof Error?e.message:"Não foi possível registrar a saída.");}finally{setBusy(false);}}
  return <div className="space-y-5">
    <header className="flex flex-wrap items-end justify-between gap-3"><div><p className="champagne-eyebrow">Portaria · operação real</p><h1 className="mt-1 font-display text-3xl">Controle do pátio</h1><p className="mt-2 text-sm text-muted-foreground">Cada entrada e saída tem placa, empresa, local, horário e trilha de auditoria.</p></div><button onClick={()=>void load()} className="inline-flex h-10 items-center gap-2 rounded-lg px-3 text-sm ring-1 ring-[color:var(--hairline)]"><RefreshCw className="h-4 w-4"/>Atualizar</button></header>
    {message&&<div className="flex items-start justify-between gap-3 rounded-xl border border-[color:var(--hairline-brand)] bg-[color:color-mix(in_oklab,var(--brand)_8%,transparent)] p-3 text-sm">{message}<button onClick={()=>setMessage(null)} aria-label="Fechar"><X className="h-4 w-4"/></button></div>}
    <div className="grid grid-cols-3 gap-3"><Metric label="No pátio" value={patio.length}/><Metric label="Registros" value={rows.length}/><Metric label="Foto entrada" value={config.fotoEntrada}/></div>
    <div className="flex gap-2 overflow-x-auto pb-1"><Tab active={mode==="patio"} onClick={()=>setMode("patio")} icon={Truck}>Pátio</Tab><Tab active={mode==="entrada"} onClick={()=>setMode("entrada")} icon={DoorOpen}>Registrar entrada</Tab><Tab active={mode==="saida"} onClick={()=>setMode("saida")} icon={LogOut}>Registrar saída</Tab></div>
    {mode==="patio"&&<section className="surface-card p-4"><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar placa, empresa ou motorista" className="field w-full pl-9"/></div><div className="mt-4 space-y-2">{rows.map(row=><button key={row.id} onClick={()=>{setSelected(row);setMode("saida")}} className="flex w-full items-center justify-between gap-3 rounded-xl p-3 text-left ring-1 ring-[color:var(--hairline)] hover:ring-[color:var(--hairline-brand)]"><span><strong className="font-mono">{row.placa}</strong><span className="ml-3 text-sm">{row.empresa_nome||row.empresa}</span><small className="mt-1 block text-xs text-muted-foreground">{row.local_nome||"Local não informado"} · {new Date(row.entrada_em).toLocaleString("pt-BR")}</small></span><span className={`rounded-full px-2 py-1 text-[10px] ${row.saida_em?"bg-muted text-muted-foreground":"bg-[color:color-mix(in_oklab,var(--success)_12%,transparent)] text-[color:var(--success)]"}`}>{row.saida_em?"saiu":"no pátio"}</span></button>)}{rows.length===0&&<p className="py-8 text-center text-sm text-muted-foreground">Nenhum registro encontrado.</p>}</div></section>}
    {mode==="entrada"&&<section className="surface-card p-4"><div className="grid gap-3 sm:grid-cols-2"><label className="field-label">Placa<input className="field mt-1 font-mono uppercase" value={plate} onChange={e=>setPlate(e.target.value.toUpperCase())} placeholder="ABC-1D23"/></label><label className="field-label">Motorista (opcional)<input className="field mt-1" value={driver} onChange={e=>setDriver(e.target.value)} placeholder="Nome completo"/></label><label className="field-label sm:col-span-2">Empresa<input className="field mt-1" value={company} onChange={e=>void searchCompany(e.target.value)} placeholder="Digite para buscar cliente ou fornecedor"/>{companies.length>0&&<div className="mt-1 max-h-40 overflow-auto rounded-lg border border-[color:var(--hairline)] bg-[color:var(--surface-elev)]">{companies.map(item=><button key={`${item.tipo}-${item.id}`} onClick={()=>{setCompany(item.nome);setCompanyId(item.id);setCompanyType(item.tipo);setCompanies([])}} className="block w-full px-3 py-2 text-left text-sm hover:bg-[color:var(--muted)]">{item.nome}<small className="ml-2 text-xs text-muted-foreground">{item.tipo}</small></button>)}</div>}</label><label className="field-label">Local operacional<select className="field mt-1" value={localId} onChange={e=>setLocalId(e.target.value)}><option value="">Selecione porto/pátio</option>{locals.map(l=><option key={l.id} value={l.id}>{l.nome} · {l.cidade_sigla}</option>)}</select></label><label className="field-label">Foto de entrada {config.fotoEntrada==="obrigatoria"?"(obrigatória)":"(opcional)"}<input className="field mt-1" type="file" accept="image/*" capture="environment" onChange={e=>setPhoto(e.target.files?.[0]||null)}/></label></div><button disabled={busy} onClick={()=>void submit()} className="mt-4 h-12 w-full rounded-xl bg-[color:var(--brand)] font-semibold text-white disabled:opacity-50">{busy?"Registrando…":"Confirmar entrada"}</button></section>}
    {mode==="saida"&&<section className="surface-card p-4"><h2 className="font-display text-xl">Saída do pátio</h2><p className="mt-1 text-sm text-muted-foreground">Selecione um veículo ainda no pátio. A operação não pode ser repetida.</p><select className="field mt-4 w-full" value={selected?.id||""} onChange={e=>setSelected(rows.find(x=>x.id===e.target.value)||null)}><option value="">Selecionar veículo</option>{patio.map(row=><option key={row.id} value={row.id}>{row.placa} · {row.empresa_nome||row.empresa}</option>)}</select><button disabled={!selected||busy} onClick={()=>void submitExit()} className="mt-4 inline-flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-[color:var(--brand)] font-semibold text-white disabled:opacity-50"><CheckCircle2 className="h-5 w-5"/>{busy?"Registrando…":"Confirmar saída"}</button></section>}
  </div>;
}
function Metric({label,value}:{label:string;value:number|string}){return <div className="surface-card p-3"><p className="text-[10px] uppercase tracking-wider text-muted-foreground">{label}</p><strong className="mt-1 block text-lg">{value}</strong></div>}
function Tab({active,onClick,icon:Icon,children}:{active:boolean;onClick:()=>void;icon:typeof Truck;children:string}){return <button onClick={onClick} className={`inline-flex h-10 shrink-0 items-center gap-2 rounded-lg px-3 text-sm ${active?"bg-[color:var(--brand)] text-white":"ring-1 ring-[color:var(--hairline)]"}`}><Icon className="h-4 w-4"/>{children}</button>}
