import { useEffect, useMemo, useState } from "react";
import { CheckCircle2, FileDown, RefreshCw } from "lucide-react";
import { SectionHeader, StatusChip, brl } from "@/components/ops/primitives";
import { conferirTmsPrestacao, getStoredAuth, getTmsPrestacaoConfig, listTmsPrestacoes, type PrestacaoConfigApi, type PrestacaoContasApi } from "@/lib/ajc-api";

const labels={rascunho:"Rascunho",enviada:"Aguardando conferência",conferida:"Conferida"};
export function PrestacaoTab(){
  const [records,setRecords]=useState<PrestacaoContasApi[]>([]);const [selected,setSelected]=useState("");const [config,setConfig]=useState<PrestacaoConfigApi|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [note,setNote]=useState("");const [busy,setBusy]=useState(false);
  const canConfer=getStoredAuth()?.user.permissions.includes("prestacao.conferir")??false;
  async function load(){setLoading(true);setError("");try{const [p,c]=await Promise.all([listTmsPrestacoes(),getTmsPrestacaoConfig()]);setRecords(p);setConfig(c);setSelected(current=>current||p[0]?.id||"");}catch(e){setError(e instanceof Error?e.message:"Falha ao carregar prestações");}finally{setLoading(false);}}
  useEffect(()=>{void load();},[]);const current=records.find(x=>x.id===selected);const receitas=current?.itens?.receitas??[];const despesas=current?.itens?.despesas??[];const revenue=useMemo(()=>receitas.reduce((s,x)=>s+Number(x.valor),0),[receitas]);const expense=useMemo(()=>despesas.reduce((s,x)=>s+Number(x.valor),0),[despesas]);
  async function confer(){if(!current)return;setBusy(true);setError("");try{await conferirTmsPrestacao(current.id,{observacao:note,clientUuid:crypto.randomUUID()});setNote("");await load();}catch(e){setError(e instanceof Error?e.message:"Falha ao conferir");}finally{setBusy(false);}}
  return <div className="space-y-5"><SectionHeader eyebrow="TMS · administração" title="Prestação de contas" description="Conferência administrativa dos fechamentos enviados pelos gerentes das embarcações." action={<button onClick={()=>void load()} className="inline-flex h-10 items-center gap-2 rounded-lg px-3 text-sm ring-1 ring-[color:var(--hairline)]"><RefreshCw className="h-4 w-4"/>Atualizar</button>}/>{error&&<p className="rounded-xl border border-[color:var(--danger)]/30 p-3 text-sm text-[color:var(--danger)]">{error}</p>}
    {loading?<div className="surface-card p-8 text-center text-sm text-muted-foreground">Carregando prestações reais...</div>:records.length===0?<div className="surface-card p-8 text-center"><h3 className="font-display text-xl">Nenhuma prestação enviada</h3><p className="mt-2 text-sm text-muted-foreground">Os rascunhos e envios do aplicativo Gerente da Embarcação aparecerão aqui.</p></div>:<div className="grid gap-4 xl:grid-cols-[20rem_1fr]">
      <aside className="space-y-2">{records.map(record=><button key={record.id} onClick={()=>setSelected(record.id)} className={`w-full rounded-xl border p-4 text-left ${selected===record.id?"border-[color:var(--brand)] bg-[color:color-mix(in_oklab,var(--brand)_8%,transparent)]":"border-[color:var(--hairline)] bg-[color:var(--surface)]"}`}><div className="flex items-center justify-between gap-2"><strong>{record.viagem_codigo}</strong><StatusChip tone={record.status==="conferida"?"success":record.status==="enviada"?"warning":"neutral"}>{labels[record.status as keyof typeof labels]??record.status}</StatusChip></div><p className="mt-2 text-xs text-muted-foreground">{record.embarcacao_nome} · {record.gerente_nome}</p><p className="mt-2 font-mono text-sm">{brl(record.total_declarado??0)}</p></button>)}</aside>
      {current&&<section className="surface-card p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="champagne-eyebrow">{current.viagem_codigo} · configuração v{current.config_versao??"—"}</p><h2 className="mt-1 font-display text-2xl">{current.embarcacao_nome}</h2><p className="mt-1 text-sm text-muted-foreground">Gerente {current.gerente_nome} · {current.origem_sigla} → {current.destino_sigla}</p></div>{config&&<button onClick={()=>printReview(current,config)} className="inline-flex h-10 items-center gap-2 rounded-lg px-3 text-sm ring-1 ring-[color:var(--hairline)]"><FileDown className="h-4 w-4"/>PDF</button>}</div>
        <div className="mt-5 grid gap-3 sm:grid-cols-3"><Metric label="Declarado" value={brl(current.total_declarado??0)}/><Metric label="Sistema" value={brl(current.total_sistema??0)}/><Metric label="Divergência" value={brl(current.divergencia??0)} danger={Boolean(current.divergencia)}/></div>
        <div className="mt-5 grid gap-5 lg:grid-cols-2"><Lines title={`Receitas · ${brl(revenue)}`} rows={receitas.map(x=>({a:config?catalogName(x.categoria,config.valor.categoriasReceita):x.categoria,b:config?catalogName(x.formaPagamento,config.valor.formasPagamento):x.formaPagamento,value:x.valor}))}/><Lines title={`Despesas · ${brl(expense)}`} rows={despesas.map(x=>({a:config?catalogName(x.categoria,config.valor.categoriasDespesa):x.categoria,b:x.escopo==="cidade"?x.cidadeSigla??"Cidade":"Viagem",value:x.valor}))}/></div>
        <div className="mt-5 border-t border-[color:var(--hairline)] pt-4"><p className="text-xs text-muted-foreground">Base operacional: {current.passageiros} passageiros · {current.cargas} cargas · {current.encomendas} encomendas · {current.veiculos} veículos.</p>{current.status==="enviada"&&canConfer&&<div className="mt-4 flex flex-col gap-3 sm:flex-row"><input className="field flex-1" placeholder="Observação da conferência (opcional)" value={note} onChange={e=>setNote(e.target.value)}/><button disabled={busy} onClick={()=>void confer()} className="inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-[color:var(--brand)] px-5 font-semibold text-white"><CheckCircle2 className="h-4 w-4"/>Confirmar conferência</button></div>}{current.observacao_conferencia&&<p className="mt-3 text-sm">Observação: {current.observacao_conferencia}</p>}</div>
      </section>}
    </div>}
  </div>;
}
function Metric({label,value,danger}:{label:string;value:string;danger?:boolean}){return <div className="rounded-xl bg-[color:var(--surface-elev)] p-4"><p className="text-[10px] uppercase tracking-wider text-muted-foreground">{label}</p><strong className={`mt-1 block text-xl ${danger?"text-[color:var(--danger)]":""}`}>{value}</strong></div>}
function Lines({title,rows}:{title:string;rows:Array<{a:string;b?:string;value:number}>}){return <div><h3 className="font-display text-lg">{title}</h3><div className="mt-2 divide-y divide-[color:var(--hairline)] rounded-xl border border-[color:var(--hairline)]">{rows.length?rows.map((x,i)=><div key={i} className="flex items-center justify-between gap-3 p-3 text-sm"><span>{x.a}<small className="ml-2 text-muted-foreground">{x.b}</small></span><strong>{brl(x.value)}</strong></div>):<p className="p-4 text-sm text-muted-foreground">Nenhum lançamento.</p>}</div></div>}
function catalogName(code:string,list:Array<{codigo:string;nome:string}>){return list.find(x=>x.codigo===code)?.nome??code}
function printReview(record:PrestacaoContasApi,config:PrestacaoConfigApi){const win=window.open("","_blank","noopener,noreferrer");if(!win)return;const rows=(record.itens?.receitas??[]).map(x=>`<tr><td>Receita</td><td>${catalogName(x.categoria,config.valor.categoriasReceita)}</td><td>${catalogName(x.formaPagamento,config.valor.formasPagamento)}</td><td>${brl(x.valor)}</td></tr>`).join("")+(record.itens?.despesas??[]).map(x=>`<tr><td>Despesa</td><td>${catalogName(x.categoria,config.valor.categoriasDespesa)}</td><td>${x.descricao}</td><td>${brl(x.valor)}</td></tr>`).join("");win.document.write(`<!doctype html><meta charset="utf-8"><title>Prestação ${record.viagem_codigo}</title><style>body{font:12px Arial;padding:28px}table{width:100%;border-collapse:collapse}th,td{border:1px solid #bbb;padding:7px;text-align:left}th{background:#eee}@media print{body{padding:0}}</style><h1>AJC · Prestação de contas</h1><p>${record.viagem_codigo} · ${record.embarcacao_nome} · ${record.gerente_nome}</p><table><tr><th>Tipo</th><th>Categoria</th><th>Detalhe</th><th>Valor</th></tr>${rows}</table><h2>Declarado ${brl(record.total_declarado??0)} · Sistema ${brl(record.total_sistema??0)} · Divergência ${brl(record.divergencia??0)}</h2><script>window.onload=()=>window.print()<\/script>`);win.document.close();}
