import { useMemo, useState } from "react";
import { Download, FileWarning, Package, Search, Ship } from "lucide-react";
import { DataTable, GhostButton, SectionHeader, StatusChip, Tag, brl } from "@/components/ops/primitives";
import type { EncomendaApi } from "@/lib/ajc-api";
import type { ViagemEncomendaUi } from "./types";

export function ControleViagemTab({ encomendas, viagens }: { encomendas: EncomendaApi[]; viagens: ViagemEncomendaUi[] }) {
  const [tripId,setTripId]=useState(""); const [query,setQuery]=useState(""); const [status,setStatus]=useState("");
  const rows=useMemo(()=>encomendas.filter((item)=>(!tripId||item.viagem_id===tripId)&&(!status||item.status_documental===status)&&normalize(`${item.codigo} ${item.remetente_nome} ${item.destinatario_nome} ${item.cidade_destino_sigla}`).includes(normalize(query))),[encomendas,tripId,status,query]);
  const summary=useMemo(()=>rows.reduce((acc,item)=>({count:acc.count+1,declared:acc.declared+item.valor_declarado,charged:acc.charged+item.valor_cobrado,pending:acc.pending+(item.status_documental!=="pronta"?1:0)}),{count:0,declared:0,charged:0,pending:0}),[rows]);
  function exportCsv(){const data=[["Protocolo","Viagem","Remetente","Destinatario","Trecho","Volumes","Declarado","Cobrado","Documento","Status"],...rows.map((item)=>[item.codigo,item.viagem_codigo,item.remetente_nome,item.destinatario_nome,`${item.cidade_origem_sigla}-${item.cidade_destino_sigla}`,item.total_volumes,item.valor_declarado,item.valor_cobrado,item.documento_tipo,item.status_documental])];const csv=data.map((line)=>line.map((value)=>`"${String(value).replaceAll('"','""')}"`).join(";")).join("\n");const url=URL.createObjectURL(new Blob(["\ufeff",csv],{type:"text/csv;charset=utf-8"}));const link=document.createElement("a");link.href=url;link.download=`encomendas-${new Date().toISOString().slice(0,10)}.csv`;link.click();URL.revokeObjectURL(url);}
  return <div className="mt-5 space-y-4"><SectionHeader eyebrow="Operação · financeiro · diretoria" title="Controle de encomendas por viagem" description="Valores e pendências vêm do domínio persistido. O filtro e a exportação usam os mesmos registros apresentados na tela." actions={<GhostButton icon={Download} disabled={!rows.length} onClick={exportCsv}>Exportar CSV</GhostButton>}/>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={Package} label="Encomendas" value={String(summary.count)}/><Metric icon={Ship} label="Valor declarado" value={brl(summary.declared)}/><Metric icon={Ship} label="Valor cobrado" value={brl(summary.charged)}/><Metric icon={FileWarning} label="Documentação pendente" value={String(summary.pending)} warning={summary.pending>0}/></div>
    <div className="surface-card flex flex-wrap gap-3 p-4"><label className="relative min-w-56 flex-1"><Search className="pointer-events-none absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><input className="field pl-9" value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Protocolo, remetente ou destinatário"/></label><select className="field w-auto min-w-52" value={tripId} onChange={(e)=>setTripId(e.target.value)}><option value="">Todas as viagens</option>{viagens.map((item)=><option key={item.id} value={item.id}>{item.codigo} · {item.embarcacaoNome}</option>)}</select><select className="field w-auto min-w-48" value={status} onChange={(e)=>setStatus(e.target.value)}><option value="">Todos os documentos</option><option value="pronta">Prontos</option><option value="aguardando_documento">Pendentes</option><option value="divergente">Divergentes</option></select></div>
    <DataTable rows={rows} empty="Nenhuma encomenda corresponde aos filtros." columns={[{key:"codigo",header:"Protocolo",render:(item)=><div><p className="font-mono text-xs text-[color:var(--brand)]">{item.codigo}</p><p className="text-[10px] text-muted-foreground">{item.viagem_codigo} · {item.embarcacao_nome}</p></div>},{key:"partes",header:"Partes",render:(item)=><div><p className="text-sm font-medium">{item.remetente_nome}</p><p className="text-xs text-muted-foreground">→ {item.destinatario_nome}</p></div>},{key:"trecho",header:"Trecho",render:(item)=><span className="font-mono text-xs">{item.cidade_origem_sigla} → {item.cidade_destino_sigla}</span>},{key:"fisico",header:"Físico",render:(item)=><Tag tone="neutral">{item.tamanho_codigo ?? "sem classificação"} · {item.total_volumes} vol · {item.peso_total} kg</Tag>},{key:"declarado",header:"Declarado",align:"right",render:(item)=><span className="font-mono text-xs">{brl(item.valor_declarado)}</span>},{key:"cobrado",header:"Cobrado",align:"right",render:(item)=><div className="text-right"><p className="font-mono text-xs text-[color:var(--brand)]">{brl(item.valor_cobrado)}</p>{item.motivo_ajuste_valor&&<p className="text-[10px] text-[color:var(--warning)]">ajustado</p>}</div>},{key:"documento",header:"Documento",render:(item)=><div><p className="text-xs font-medium">{item.documento_tipo ? `${item.documento_tipo} ${item.documento_numero??""}` : "não registrado"}</p><StatusChip size="xs" tone={item.status_documental==="pronta"?"success":item.status_documental==="divergente"?"danger":"warning"}>{item.status_documental==="pronta"?"pronto":item.status_documental==="divergente"?"divergente":item.status_documental==="legado_incompleto"?"legado incompleto":"pendente"}</StatusChip></div>}]} /></div>;
}
function Metric({icon:Icon,label,value,warning=false}:{icon:typeof Package;label:string;value:string;warning?:boolean}){return <div className="surface-card flex items-center gap-3 p-4"><span className={`grid h-10 w-10 place-items-center rounded-lg ring-1 ring-[color:var(--hairline)] ${warning?"text-[color:var(--warning)]":"text-[color:var(--brand)]"}`}><Icon className="h-5 w-5"/></span><div><p className="big-numeric text-xl">{value}</p><p className="text-xs text-muted-foreground">{label}</p></div></div>}
function normalize(value:string){return value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/\W/g,"");}
