import { useEffect, useMemo, useState } from "react";
import { ArrowRight, Calculator, CalendarClock, Save, Search, Ship } from "lucide-react";
import { GhostButton, PrimaryButton, SectionHeader, Tag } from "@/components/ops/primitives";
import { createCrmCotacao } from "@/lib/ajc-api";
import { calcularPrecoEncomenda, sugerirTamanhoPorPeso } from "./pricing";
import { PrecoDestaque } from "./shared";
import type { ClienteEncomendaUi, EncomendaConfigUi, PrecoEncomendaTabela, ViagemEncomendaUi } from "./types";

export type CotacaoParaDespacho = { cotacaoId: string; clienteId: string; trecho: string; tamanhoCodigo: string; peso: number; valorDeclarado: number; valorEstimado: number };
export function CotacaoTab({ onConverter, clientes, viagens, precos, config }: { onConverter: (draft: CotacaoParaDespacho) => void; clientes: ClienteEncomendaUi[]; viagens: ViagemEncomendaUi[]; precos: PrecoEncomendaTabela[]; config: EncomendaConfigUi }) {
  const [query, setQuery] = useState(""); const [clienteId, setClienteId] = useState("");
  const [trecho, setTrecho] = useState(""); const [tamanho, setTamanho] = useState(config.tamanhos.find((item) => item.ativo)?.codigo ?? "");
  const [peso, setPeso] = useState(0); const [valor, setValor] = useState(0); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [saved, setSaved] = useState<CotacaoParaDespacho | null>(null);
  const rows = useMemo(() => clientes.filter((item) => normalize(`${item.nome} ${item.documento} ${item.codigo}`).includes(normalize(query))).slice(0, 30), [clientes, query]);
  const result = useMemo(() => calcularPrecoEncomenda(precos, { trecho, tamanho, valorDeclarado: valor, limiteFixo: config.limiteValorFixo }), [precos, trecho, tamanho, valor, config.limiteValorFixo]);
  const [origem, destino] = trecho.split("->").map((item) => item.trim());
  const trip = viagens.find((item) => ["planejada","em_curso"].includes(item.status) && includesCity(item, origem) && includesCity(item, destino));
  useEffect(() => { const suggested = sugerirTamanhoPorPeso(config.tamanhos, peso); if (suggested) setTamanho(suggested); }, [peso, config.tamanhos]);
  async function save() { if (!clienteId || !result || !origem || !destino) return; setSaving(true); setMessage(""); try { const row = await createCrmCotacao({ tipo: "encomenda", clienteId, origemSigla: origem, destinoSigla: destino, valorEstimado: result.preco, clientUuid: crypto.randomUUID(), parametros: { trecho, tamanho, peso, valorDeclarado: valor, tabelaVersao: result.tabelaVersao, modoPreco: result.modo, proximaViagemId: trip?.id ?? null } }); const draft = { cotacaoId: row.id, clienteId, trecho, tamanhoCodigo: tamanho, peso, valorDeclarado: valor, valorEstimado: result.preco }; setSaved(draft); setMessage(`Cotação ${row.id.slice(0,8).toUpperCase()} registrada.`); } catch (error) { setMessage(error instanceof Error ? error.message : "Falha ao salvar cotação"); } finally { setSaving(false); } }
  return <div className="mt-5 space-y-4"><SectionHeader eyebrow="Atendimento · sem reservar espaço" title="Cotação de encomenda" description="Simule com a tabela publicada. Ao converter, cliente, trecho, tamanho, peso e valor seguem para o despacho sem redigitação."/>
    <div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_360px]"><section className="surface-card p-5"><div className="flex items-center gap-2"><Calculator className="h-4 w-4 text-[color:var(--brand)]"/><h3 className="font-semibold">Dados da cotação</h3></div>
      <label className="mt-4 block text-xs text-muted-foreground">Buscar cliente</label><div className="relative mt-1"><Search className="pointer-events-none absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><input className="field pl-9" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Nome, código ou CPF/CNPJ"/></div>
      {query && <div className="mt-2 max-h-48 overflow-auto rounded-lg ring-1 ring-[color:var(--hairline)]">{rows.map((item) => <button key={item.id} onClick={() => { setClienteId(item.id); setQuery(item.nome); }} className={`block w-full px-3 py-2 text-left text-sm hover:bg-[color:var(--accent)] ${clienteId === item.id ? "bg-[color:color-mix(in_oklab,var(--brand)_10%,transparent)]" : ""}`}><span className="font-medium">{item.nome}</span><span className="ml-2 text-xs text-muted-foreground">{item.codigo} · {item.documento}</span></button>)}</div>}
      <label className="mt-4 block text-xs text-muted-foreground">Trecho publicado</label><select className="field mt-1" value={trecho} onChange={(e) => setTrecho(e.target.value)}><option value="">Selecione</option>{precos.map((item) => <option key={item.trecho}>{item.trecho}</option>)}</select>
      <div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-xs text-muted-foreground">Peso (kg)<input className="field mt-1" type="number" min="0.001" step="0.001" value={peso || ""} onChange={(e) => setPeso(Number(e.target.value))}/></label><label className="text-xs text-muted-foreground">Valor declarado<input className="field mt-1" type="number" min="0.01" step="0.01" value={valor || ""} onChange={(e) => setValor(Number(e.target.value))}/></label></div>
      <label className="mt-4 block text-xs text-muted-foreground">Tamanho</label><div className="mt-2 flex flex-wrap gap-2">{config.tamanhos.filter((item) => item.ativo).map((item) => <button key={item.codigo} onClick={() => setTamanho(item.codigo)} className={`rounded-lg px-3 py-2 text-sm ring-1 ${tamanho === item.codigo ? "text-[color:var(--brand)] ring-[color:var(--hairline-brand)]" : "ring-[color:var(--hairline)]"}`}><strong>{item.codigo}</strong> · até {item.pesoMaxKg} kg</button>)}</div>
      <p className="mt-4 text-xs text-muted-foreground"><Tag tone="neutral">cotação não cria envio</Tag> A reserva só nasce no despacho.</p></section>
      <aside className="space-y-4"><PrecoDestaque resultado={result} trecho={trecho} tamanho={tamanho}/><div className="surface-card p-4"><div className="flex items-center gap-2"><CalendarClock className="h-4 w-4 text-[color:var(--brand)]"/><h3 className="font-semibold">Próxima viagem compatível</h3></div>{trip ? <div className="mt-3"><p className="inline-flex items-center gap-2 text-sm font-medium"><Ship className="h-4 w-4"/>{trip.codigo} · {trip.embarcacaoNome}</p><p className="mt-1 text-xs text-muted-foreground">{origem} → {destino}</p></div> : <p className="mt-3 text-sm text-muted-foreground">Nenhuma viagem ativa cobre o trecho. A cotação pode ser salva, mas o despacho exigirá viagem.</p>}</div>
        <div className="flex flex-wrap gap-2"><PrimaryButton icon={Save} disabled={!clienteId || !result || saving} onClick={save}>{saving ? "Salvando…" : "Salvar cotação"}</PrimaryButton><GhostButton icon={ArrowRight} disabled={!saved} onClick={() => saved && onConverter(saved)}>Converter</GhostButton></div>{message && <p className="rounded-lg bg-[color:var(--muted)] p-3 text-xs text-muted-foreground">{message}</p>}</aside></div></div>;
}
function includesCity(trip: ViagemEncomendaUi, city: string) { return trip.origem === city || trip.destino === city || trip.escalas.some((item) => item.cidade === city); }
function normalize(value: string) { return value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/\W/g, ""); }
