import { useEffect, useRef, useState } from "react";
import { CheckCircle2, Eraser, FileSignature, PenLine } from "lucide-react";
import { GhostButton, PrimaryButton, SectionHeader, StatusChip, brl } from "@/components/ops/primitives";
import { saveEncomendaDeclaracao, uploadEncomendaEvidence, type EncomendaApi } from "@/lib/ajc-api";
import { ResumoLinha, TermoDC } from "./shared";
import type { EncomendaConfigUi } from "./types";

export function DeclaracaoTab({ encomendas, config, onSaved }: { encomendas: EncomendaApi[]; config: EncomendaConfigUi; onSaved: () => Promise<void> | void }) {
  const pending = encomendas.filter((item) => item.documento_tipo === "DC" && !item.dc_assinada);
  const [selectedId, setSelectedId] = useState(pending[0]?.id ?? "");
  const selected = encomendas.find((item) => item.id === selectedId) ?? pending[0];
  return <div className="mt-5 space-y-4"><SectionHeader eyebrow="Documento legal · assinatura real" title="Declaração de Conteúdo" description="O termo exibido é exatamente a versão publicada em Cadastros. A assinatura desenhada é enviada ao storage privado e o hash integra a trilha de auditoria."/>
    <TermoDC config={config}/>
    <div className="grid gap-4 lg:grid-cols-[300px_minmax(0,1fr)]"><aside className="surface-card p-3"><p className="px-2 py-1 text-xs font-medium text-muted-foreground">Pendentes de assinatura</p><div className="mt-2 space-y-1">{pending.length ? pending.map((item) => <button key={item.id} onClick={() => setSelectedId(item.id)} className={`w-full rounded-lg px-3 py-2 text-left ring-1 ${selected?.id === item.id ? "bg-[color:color-mix(in_oklab,var(--brand)_10%,transparent)] ring-[color:var(--hairline-brand)]" : "ring-transparent hover:bg-[color:var(--accent)]"}`}><p className="font-mono text-xs text-[color:var(--brand)]">{item.codigo}</p><p className="mt-1 truncate text-sm">{item.remetente_nome} → {item.destinatario_nome}</p></button>) : <div className="p-4 text-center text-sm text-muted-foreground"><CheckCircle2 className="mx-auto mb-2 h-5 w-5 text-[color:var(--success)]"/>Nenhuma DC pendente.</div>}</div></aside>
      <section className="surface-card p-5">{selected ? <><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-mono text-xs text-[color:var(--brand)]">{selected.codigo}</p><h3 className="mt-1 font-display text-xl">Confirmação do remetente</h3></div><StatusChip tone={config.termo.publicado ? "warning" : "danger"}>{config.termo.publicado ? "aguardando assinatura" : "termo não publicado"}</StatusChip></div><div className="mt-4 grid gap-x-8 md:grid-cols-2"><ResumoLinha label="Remetente">{selected.remetente_nome}</ResumoLinha><ResumoLinha label="CPF/CNPJ">{selected.remetente_documento}</ResumoLinha><ResumoLinha label="Destinatário">{selected.destinatario_nome}</ResumoLinha><ResumoLinha label="Trecho">{selected.cidade_origem_sigla} → {selected.cidade_destino_sigla}</ResumoLinha><ResumoLinha label="Conteúdo">{selected.conteudo_declarado}</ResumoLinha><ResumoLinha label="Valor declarado">{brl(selected.valor_declarado)}</ResumoLinha></div><SignatureCapture disabled={!config.termo.publicado} encomendaId={selected.id} onSaved={async () => { await onSaved(); const next = pending.find((item) => item.id !== selected.id); setSelectedId(next?.id ?? ""); }}/></> : <div className="grid min-h-72 place-items-center text-center text-sm text-muted-foreground"><div><FileSignature className="mx-auto mb-3 h-7 w-7"/><p>Selecione uma encomenda com DC pendente.</p></div></div>}</section></div></div>;
}

function SignatureCapture({ disabled, encomendaId, onSaved }: { disabled: boolean; encomendaId: string; onSaved: () => Promise<void> | void }) {
  const canvas = useRef<HTMLCanvasElement>(null); const drawing = useRef(false); const [hasStroke, setHasStroke] = useState(false); const [accept, setAccept] = useState(false); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  useEffect(() => { clear(); }, [encomendaId]);
  function point(event: React.PointerEvent<HTMLCanvasElement>) { const rect = event.currentTarget.getBoundingClientRect(); return { x: (event.clientX - rect.left) * (event.currentTarget.width / rect.width), y: (event.clientY - rect.top) * (event.currentTarget.height / rect.height) }; }
  function start(event: React.PointerEvent<HTMLCanvasElement>) { if (disabled) return; drawing.current = true; event.currentTarget.setPointerCapture(event.pointerId); const ctx = event.currentTarget.getContext("2d")!; const p = point(event); ctx.beginPath(); ctx.moveTo(p.x,p.y); }
  function move(event: React.PointerEvent<HTMLCanvasElement>) { if (!drawing.current) return; const ctx = event.currentTarget.getContext("2d")!; const p = point(event); ctx.lineWidth=3; ctx.lineCap="round"; ctx.lineJoin="round"; ctx.strokeStyle="#f2eee9"; ctx.lineTo(p.x,p.y); ctx.stroke(); setHasStroke(true); }
  function stop() { drawing.current=false; }
  function clear() { const el=canvas.current; if (!el) return; const ctx=el.getContext("2d")!; ctx.clearRect(0,0,el.width,el.height); setHasStroke(false); setAccept(false); setMessage(""); }
  async function save() { const el=canvas.current; if (!el || !hasStroke || !accept) return; setSaving(true); setMessage(""); try { const blob=await new Promise<Blob>((resolve,reject)=>el.toBlob((value)=>value?resolve(value):reject(new Error("Falha ao gerar assinatura")),"image/png")); const file=new File([blob],`assinatura-${encomendaId}.png`,{type:"image/png"}); const evidence=await uploadEncomendaEvidence(file,"assinatura_dc"); await saveEncomendaDeclaracao(encomendaId,{ evidenciaAssinaturaId:evidence.id, aceiteEm:new Date().toISOString(), dispositivo:navigator.userAgent.slice(0,120), clientUuid:crypto.randomUUID() }); setMessage("Declaração assinada e vinculada com sucesso."); await onSaved(); } catch (error) { setMessage(error instanceof Error?error.message:"Falha ao assinar DC"); } finally { setSaving(false); } }
  return <div className="mt-5"><div className="mb-2 flex items-center justify-between gap-2"><span className="inline-flex items-center gap-2 text-sm font-medium"><PenLine className="h-4 w-4 text-[color:var(--brand)]"/>Assinatura do remetente</span><GhostButton icon={Eraser} onClick={clear}>Limpar</GhostButton></div><canvas ref={canvas} width={900} height={260} onPointerDown={start} onPointerMove={move} onPointerUp={stop} onPointerCancel={stop} className={`h-44 w-full touch-none rounded-xl bg-[color:var(--surface-deep)] ring-1 ring-[color:var(--hairline-strong)] ${disabled?"cursor-not-allowed opacity-50":"cursor-crosshair"}`} aria-label="Área para assinatura em tela"/><label className="mt-3 flex items-start gap-2 text-sm text-foreground/85"><input type="checkbox" className="mt-1 accent-[color:var(--brand)]" checked={accept} disabled={disabled} onChange={(e)=>setAccept(e.target.checked)}/><span>Li o termo publicado e confirmo que conteúdo, valor, remetente e destinatário estão corretos.</span></label><PrimaryButton icon={FileSignature} className="mt-4" disabled={disabled || !hasStroke || !accept || saving} onClick={save}>{saving?"Salvando assinatura…":"Assinar e concluir DC"}</PrimaryButton>{message&&<p className="mt-3 rounded-lg bg-[color:var(--muted)] p-3 text-sm text-muted-foreground">{message}</p>}</div>;
}
