import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, Camera, CheckCircle2, FileText, PackagePlus, Search, UserPlus, Wallet } from "lucide-react";
import { GhostButton, PrimaryButton, SectionHeader, StatusChip, Tag, brl } from "@/components/ops/primitives";
import { createCliente, createEncomenda, uploadEncomendaEvidence, type EncomendaEvidenceApi } from "@/lib/ajc-api";
import { calcularPrecoEncomenda, sugerirTamanhoPorPeso } from "./pricing";
import { PrecoDestaque, ResumoLinha } from "./shared";
import type { CotacaoParaDespacho } from "./CotacaoTab";
import type { ClienteEncomendaUi, EncomendaConfigUi, PrecoEncomendaTabela, ViagemEncomendaUi } from "./types";

export function DespachoTab({ clientes, viagens, precos, config, conversao, onCreated }: { clientes: ClienteEncomendaUi[]; viagens: ViagemEncomendaUi[]; precos: PrecoEncomendaTabela[]; config: EncomendaConfigUi; conversao: CotacaoParaDespacho | null; onCreated: () => void }) {
  const [query, setQuery] = useState(""); const [clienteId, setClienteId] = useState(""); const [novo, setNovo] = useState(false);
  const [remetente, setRemetente] = useState(""); const [remDoc, setRemDoc] = useState(""); const [remTel, setRemTel] = useState("");
  const [destinatario, setDestinatario] = useState(""); const [destDoc, setDestDoc] = useState(""); const [destTel, setDestTel] = useState("");
  const [trecho, setTrecho] = useState(""); const [viagemId, setViagemId] = useState(""); const [tamanho, setTamanho] = useState(config.tamanhos.find((item) => item.ativo)?.codigo ?? "");
  const [peso, setPeso] = useState(0); const [volumes, setVolumes] = useState(1); const [valorDeclarado, setValorDeclarado] = useState(0); const [conteudo, setConteudo] = useState("");
  const [quemPaga, setQuemPaga] = useState<"remetente"|"destinatario">("remetente"); const [forma, setForma] = useState(config.formasPagamento.find((item) => item.ativo)?.codigo ?? "");
  const [documentoTipo, setDocumentoTipo] = useState<"NF"|"DC">("DC"); const [documentoNumero, setDocumentoNumero] = useState("");
  const [foto, setFoto] = useState<EncomendaEvidenceApi | null>(null); const [documento, setDocumento] = useState<EncomendaEvidenceApi | null>(null); const [uploading, setUploading] = useState<"foto"|"documento"|null>(null);
  const [valorCobrado, setValorCobrado] = useState(0); const [motivo, setMotivo] = useState(""); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  const results = useMemo(() => clientes.filter((item) => normalize(`${item.nome} ${item.documento} ${item.codigo}`).includes(normalize(query))).slice(0, 40), [clientes, query]);
  const calculated = useMemo(() => calcularPrecoEncomenda(precos, { trecho, tamanho, valorDeclarado, limiteFixo: config.limiteValorFixo }), [precos, trecho, tamanho, valorDeclarado, config.limiteValorFixo]);
  useEffect(() => { if (calculated) setValorCobrado(calculated.preco); }, [calculated]);
  useEffect(() => { const suggested = sugerirTamanhoPorPeso(config.tamanhos, peso); if (suggested) setTamanho(suggested); }, [peso, config.tamanhos]);
  useEffect(() => { if (!conversao) return; setClienteId(conversao.clienteId); const client = clientes.find((item) => item.id === conversao.clienteId); if (client) selectClient(client); setTrecho(conversao.trecho); setTamanho(conversao.tamanhoCodigo); setPeso(conversao.peso); setValorDeclarado(conversao.valorDeclarado); setValorCobrado(conversao.valorEstimado); }, [conversao, clientes]);
  const [origem, destino] = trecho.split("->").map((item) => item.trim());
  const compatibleTrips = viagens.filter((trip) => ["planejada","em_curso"].includes(trip.status) && includesCity(trip, origem) && includesCity(trip, destino));
  useEffect(() => { if (!compatibleTrips.some((item) => item.id === viagemId)) setViagemId(compatibleTrips[0]?.id ?? ""); }, [trecho, viagens]);
  const size = config.tamanhos.find((item) => item.codigo === tamanho); const adjusted = calculated ? Math.abs(valorCobrado - calculated.preco) > .009 : false;
  const overEncomendaWeight = peso > config.limitePesoEncomenda;
  const ready = Boolean(remetente && remDoc && remTel && destinatario && destDoc && destTel && origem && destino && viagemId && size && !overEncomendaWeight && peso > 0 && peso <= size.pesoMaxKg && volumes > 0 && valorDeclarado > 0 && conteudo && calculated && valorCobrado >= 0 && (!adjusted || motivo.trim()) && foto && (documentoTipo === "DC" ? config.termo.publicado : documento) && (quemPaga === "destinatario" || forma) && !saving);
  function selectClient(item: ClienteEncomendaUi) { setClienteId(item.id); setNovo(false); setQuery(item.nome); setRemetente(item.nome); setRemDoc(item.documento); setRemTel(item.telefone ?? ""); }
  async function upload(file: File, kind: "foto"|"documento") { setUploading(kind); setMessage(""); try { const row = await uploadEncomendaEvidence(file, kind === "foto" ? "foto_encomenda" : documentoTipo === "NF" ? "documento_nf" : "documento_dc"); kind === "foto" ? setFoto(row) : setDocumento(row); } catch (error) { setMessage(error instanceof Error ? error.message : "Falha no upload"); } finally { setUploading(null); } }
  async function save() { if (!ready || !calculated) return; setSaving(true); setMessage(""); try { let actualClientId = clienteId; if (novo) { const created = await createCliente({ tipo: remDoc.replace(/\D/g,"").length > 11 ? "PJ" : "PF", nome: remetente, cpfCnpj: remDoc, cidadeSigla: origem, contatos: [{ tipo: "telefone", valor: remTel }] }); actualClientId = created.id; } await createEncomenda({ viagemId, clienteRemetenteId: actualClientId, remetenteNome: remetente, remetenteDocumento: remDoc, remetenteTelefone: remTel, destinatarioNome: destinatario, destinatarioDocumento: destDoc, destinatarioTelefone: destTel, cidadeOrigemSigla: origem, cidadeDestinoSigla: destino, tamanhoCodigo: tamanho, pesoTotal: peso, totalVolumes: volumes, valorDeclarado, valorCobrado, motivoAjusteValor: adjusted ? motivo : undefined, conteudoDeclarado: conteudo, quemPaga, formaPagamento: quemPaga === "remetente" ? forma : undefined, documentoTipo, documentoNumero: documentoNumero || undefined, evidenciaFotoId: foto!.id, evidenciaDocumentoId: documento?.id, cotacaoId: conversao?.cotacaoId, clientUuid: crypto.randomUUID() }); setMessage(documentoTipo === "DC" ? "Despacho criado. A DC precisa ser assinada na aba Documentos e assinatura antes de avançar." : "Despacho criado com NF e foto vinculadas."); reset(); onCreated(); } catch (error) { setMessage(error instanceof Error ? error.message : "Não foi possível criar o despacho"); } finally { setSaving(false); } }
  function reset() { setClienteId(""); setNovo(false); setQuery(""); setRemetente(""); setRemDoc(""); setRemTel(""); setDestinatario(""); setDestDoc(""); setDestTel(""); setTrecho(""); setViagemId(""); setPeso(0); setVolumes(1); setValorDeclarado(0); setConteudo(""); setFoto(null); setDocumento(null); setDocumentoNumero(""); setMotivo(""); }
  return <div className="mt-5 space-y-4"><SectionHeader eyebrow="Balcão · cadastro definitivo" title={conversao ? "Converter cotação em despacho" : "Novo despacho de encomenda"} description="Dados estruturados, preço recalculado pelo servidor, foto e documento em storage privado. Nenhuma assinatura ou leitura de balança é simulada."/>
    {conversao && <div className="rounded-lg bg-[color:color-mix(in_oklab,var(--info)_9%,transparent)] p-3 text-sm ring-1 ring-[color:color-mix(in_oklab,var(--info)_25%,transparent)]">Cotação {conversao.cotacaoId.slice(0,8).toUpperCase()} carregada. Complete destinatário, documento, foto e pagamento.</div>}
    <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_380px]"><div className="space-y-4">
      <Panel title="1. Remetente" icon={Search}><label className="text-xs text-muted-foreground">Buscar cliente existente</label><input className="field mt-1" value={query} onChange={(e) => { setQuery(e.target.value); setClienteId(""); }} placeholder="Nome, código ou CPF/CNPJ"/>{query && !clienteId && !novo && <div className="mt-2 max-h-52 overflow-auto rounded-lg ring-1 ring-[color:var(--hairline)]">{results.map((item) => <button key={item.id} onClick={() => selectClient(item)} className="block w-full px-3 py-2 text-left hover:bg-[color:var(--accent)]"><span className="text-sm font-medium">{item.nome}</span><span className="ml-2 text-xs text-muted-foreground">{item.codigo} · {item.documento}</span></button>)}<button onClick={() => { setNovo(true); setClienteId(""); setRemetente(query); }} className="flex w-full items-center gap-2 border-t border-[color:var(--hairline)] px-3 py-2 text-sm text-[color:var(--brand)]"><UserPlus className="h-4 w-4"/>Cadastrar “{query}”</button></div>}<div className="mt-3 grid gap-3 sm:grid-cols-3"><Field label="Nome / razão social"><input className="field" value={remetente} onChange={(e) => setRemetente(e.target.value)} disabled={Boolean(clienteId)}/></Field><Field label="CPF/CNPJ"><input className="field" value={remDoc} onChange={(e) => setRemDoc(e.target.value)} disabled={Boolean(clienteId)}/></Field><Field label="Telefone"><input className="field" value={remTel} onChange={(e) => setRemTel(e.target.value)}/></Field></div>{novo && <p className="mt-2 text-xs text-muted-foreground">O cliente será cadastrado pela mesma ação do despacho.</p>}</Panel>
      <Panel title="2. Destinatário" icon={PackagePlus}><div className="grid gap-3 sm:grid-cols-3"><Field label="Nome / razão social"><input className="field" value={destinatario} onChange={(e) => setDestinatario(e.target.value)}/></Field><Field label="CPF/CNPJ"><input className="field" value={destDoc} onChange={(e) => setDestDoc(e.target.value)}/></Field><Field label="Telefone"><input className="field" value={destTel} onChange={(e) => setDestTel(e.target.value)}/></Field></div></Panel>
      <Panel title="3. Viagem e dimensionamento" icon={PackagePlus}><div className="grid gap-3 md:grid-cols-2"><Field label="Trecho com preço publicado"><select className="field" value={trecho} onChange={(e) => setTrecho(e.target.value)}><option value="">Selecione</option>{precos.map((item) => <option key={item.trecho}>{item.trecho}</option>)}</select></Field><Field label="Viagem compatível"><select className="field" value={viagemId} onChange={(e) => setViagemId(e.target.value)}><option value="">Selecione</option>{compatibleTrips.map((item) => <option key={item.id} value={item.id}>{item.codigo} · {item.embarcacaoNome}</option>)}</select></Field></div><div className="mt-3 grid gap-3 sm:grid-cols-3"><Field label="Peso real (kg)"><input className="field" type="number" min="0.001" step="0.001" value={peso || ""} onChange={(e) => setPeso(Number(e.target.value))}/></Field><Field label="Volumes"><input className="field" type="number" min="1" step="1" value={volumes} onChange={(e) => setVolumes(Number(e.target.value))}/></Field><Field label="Valor declarado"><input className="field" type="number" min="0.01" step="0.01" value={valorDeclarado || ""} onChange={(e) => setValorDeclarado(Number(e.target.value))}/></Field></div><div className="mt-3 flex flex-wrap gap-2">{config.tamanhos.filter((item) => item.ativo).map((item) => <button key={item.codigo} onClick={() => setTamanho(item.codigo)} className={`rounded-lg px-3 py-2 text-sm ring-1 ${tamanho === item.codigo ? "text-[color:var(--brand)] ring-[color:var(--hairline-brand)]" : "ring-[color:var(--hairline)]"}`}><strong>{item.codigo}</strong> · {item.nome} · até {item.pesoMaxKg} kg</button>)}</div>{size && peso > size.pesoMaxKg && <p className="mt-3 inline-flex items-center gap-2 text-sm text-[color:var(--danger)]"><AlertTriangle className="h-4 w-4"/>O peso ultrapassa o limite publicado do tamanho.</p>}<Field label="Conteúdo declarado" className="mt-3"><textarea className="min-h-20 w-full rounded-xl bg-[color:var(--surface-elev)] p-3 text-sm ring-1 ring-[color:var(--hairline)] focus:outline-none focus:ring-[color:var(--ring)]" value={conteudo} onChange={(e) => setConteudo(e.target.value)}/></Field></Panel>
      <Panel title="4. Documento e foto" icon={FileText}><div className="flex gap-2">{(["DC","NF"] as const).map((kind) => <button key={kind} onClick={() => { setDocumentoTipo(kind); setDocumento(null); }} className={`h-10 rounded-lg px-4 text-sm ring-1 ${documentoTipo === kind ? "text-[color:var(--brand)] ring-[color:var(--hairline-brand)]" : "ring-[color:var(--hairline)]"}`}>{kind === "DC" ? "Declaração de Conteúdo" : "Nota Fiscal"}</button>)}</div>{documentoTipo === "DC" && !config.termo.publicado && <p className="mt-3 text-sm text-[color:var(--warning)]">O termo final ainda não foi publicado em Cadastros. Despachos com DC permanecem bloqueados.</p>}<div className="mt-3 grid gap-3 sm:grid-cols-2"><Upload label="Foto real da encomenda" icon={Camera} accept="image/jpeg,image/png,image/webp" value={foto} loading={uploading === "foto"} onFile={(file) => upload(file,"foto")}/><Upload label={documentoTipo === "NF" ? "XML, PDF ou foto da NF" : "Foto/PDF de DC externa (opcional)"} icon={FileText} accept=".xml,.pdf,image/jpeg,image/png,image/webp" value={documento} loading={uploading === "documento"} onFile={(file) => upload(file,"documento")}/></div>{documentoTipo === "NF" && <Field label="Número/chave da NF" className="mt-3"><input className="field" value={documentoNumero} onChange={(e) => setDocumentoNumero(e.target.value)}/></Field>}</Panel>
      <Panel title="5. Pagamento" icon={Wallet}><div className="grid gap-2 sm:grid-cols-2">{(["remetente","destinatario"] as const).map((item) => <button key={item} onClick={() => setQuemPaga(item)} className={`h-11 rounded-lg text-sm font-medium ring-1 ${quemPaga === item ? "text-[color:var(--brand)] ring-[color:var(--hairline-brand)]" : "ring-[color:var(--hairline)]"}`}>{item === "remetente" ? "Remetente paga agora" : "Destinatário paga no destino"}</button>)}</div>{quemPaga === "remetente" ? <Field label="Forma de pagamento" className="mt-3"><select className="field" value={forma} onChange={(e) => setForma(e.target.value)}>{config.formasPagamento.filter((item) => item.ativo).map((item) => <option key={item.codigo} value={item.codigo}>{item.nome}</option>)}</select><p className="mt-1 text-xs text-muted-foreground">Exige caixa aberto do operador e lança o movimento automaticamente.</p></Field> : <p className="mt-3 text-xs text-muted-foreground">Será criado um título em Contas a Receber com o prazo publicado.</p>}</Panel>
    </div><aside className="space-y-4 xl:sticky xl:top-20 xl:self-start"><PrecoDestaque resultado={calculated} trecho={trecho} tamanho={tamanho}/><section className="surface-card p-5"><h3 className="font-semibold">Valor cobrável</h3><label className="mt-3 block text-xs text-muted-foreground">Valor final<input className="field mt-1" type="number" min="0" step="0.01" value={valorCobrado || ""} onChange={(e) => setValorCobrado(Number(e.target.value))}/></label>{adjusted && <label className="mt-3 block text-xs text-muted-foreground">Motivo obrigatório do ajuste<textarea className="mt-1 min-h-20 w-full rounded-xl bg-[color:var(--surface-elev)] p-3 text-sm ring-1 ring-[color:var(--hairline)]" value={motivo} onChange={(e) => setMotivo(e.target.value)}/></label>}<div className="mt-4"><ResumoLinha label="Tabela">{brl(calculated?.preco ?? 0)}</ResumoLinha><ResumoLinha label="Cobrar">{brl(valorCobrado)}</ResumoLinha><ResumoLinha label="Documento">{documentoTipo}</ResumoLinha><ResumoLinha label="Pagamento">{quemPaga}</ResumoLinha><ResumoLinha label="Foto">{foto ? "anexada" : "pendente"}</ResumoLinha></div><PrimaryButton icon={CheckCircle2} disabled={!ready} onClick={save} className="mt-4 w-full">{saving ? "Criando…" : "Confirmar despacho"}</PrimaryButton>{!ready && <p className="mt-2 text-xs leading-relaxed text-muted-foreground">Preencha as partes, selecione viagem/tabela, anexe a foto e o documento exigido. Ajustes de preço precisam de motivo.</p>}{message && <p className="mt-3 rounded-lg bg-[color:var(--muted)] p-3 text-xs text-muted-foreground">{message}</p>}</section></aside></div></div>;
}
function Panel({ title, icon: Icon, children }: { title: string; icon: typeof Search; children: React.ReactNode }) { return <section className="surface-card p-5"><div className="mb-4 flex items-center gap-2"><Icon className="h-4 w-4 text-[color:var(--brand)]"/><h3 className="font-semibold">{title}</h3></div>{children}</section>; }
function Field({ label, className="", children }: { label: string; className?: string; children: React.ReactNode }) { return <label className={`block text-xs text-muted-foreground ${className}`}>{label}<div className="mt-1">{children}</div></label>; }
function Upload({ label, icon: Icon, accept, value, loading, onFile }: { label: string; icon: typeof Camera; accept: string; value: EncomendaEvidenceApi|null; loading: boolean; onFile:(file:File)=>void }) { return <label className="grid min-h-28 cursor-pointer place-items-center rounded-xl border border-dashed border-[color:var(--hairline-strong)] bg-[color:var(--surface-tint)] p-3 text-center"><input type="file" className="sr-only" accept={accept} onChange={(e) => e.target.files?.[0] && onFile(e.target.files[0])}/>{value ? <><CheckCircle2 className="h-5 w-5 text-[color:var(--success)]"/><span className="text-xs font-medium">{value.arquivo_nome}</span><StatusChip tone="success" size="xs">SHA-256 registrado</StatusChip></> : <><Icon className="h-5 w-5 text-[color:var(--brand)]"/><span className="text-xs font-medium">{loading ? "Enviando…" : label}</span><Tag tone="neutral">até 12 MB</Tag></>}</label>; }
function includesCity(trip: ViagemEncomendaUi, city: string) { return Boolean(city) && (trip.origem === city || trip.destino === city || trip.escalas.some((item) => item.cidade === city)); }
function normalize(value: string) { return value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/\W/g,""); }
