import { useEffect, useState } from "react";
import { CheckCircle2, Clock, FileText, MapPin, Package, Search, User } from "lucide-react";
import { SectionHeader, StatusChip, Tag, brl } from "@/components/ops/primitives";
import { getEncomendaDetail, type EncomendaApi, type EncomendaDetailApi } from "@/lib/ajc-api";

export function RastreamentoTab({ encomendas }: { encomendas: EncomendaApi[] }) {
  const [query,setQuery]=useState(""); const [selected,setSelected]=useState(encomendas[0]?.id??""); const [detail,setDetail]=useState<EncomendaDetailApi|null>(null); const [error,setError]=useState("");
  useEffect(()=>{if(!selected){setDetail(null);return;} let alive=true;setError("");getEncomendaDetail(selected).then((row)=>alive&&setDetail(row)).catch((reason)=>alive&&setError(reason instanceof Error?reason.message:"Falha ao carregar rastreio"));return()=>{alive=false}},[selected]);
  const rows=encomendas.filter((item)=>normalize(`${item.codigo} ${item.remetente_nome} ${item.destinatario_nome}`).includes(normalize(query)));
  const events=detail?.eventos.filter((item)=>item.id||item.entrega_protocolo)??[];
  return <div className="mt-5 space-y-4"><SectionHeader eyebrow="Atendimento · mesma trilha do TMS" title="Rastreamento da encomenda" description="A linha do tempo é formada por eventos físicos dos volumes. Estados não ocorridos não são apresentados como concluídos e notificações externas não são fingidas."/>
    <div className="grid gap-4 lg:grid-cols-[320px_minmax(0,1fr)]"><aside className="surface-card p-3"><label className="relative block"><Search className="pointer-events-none absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><input className="field pl-9" value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Protocolo ou pessoa"/></label><div className="mt-2 max-h-[620px] space-y-1 overflow-auto">{rows.map((item)=><button key={item.id} onClick={()=>setSelected(item.id)} className={`w-full rounded-lg px-3 py-2 text-left ring-1 ${selected===item.id?"bg-[color:color-mix(in_oklab,var(--brand)_10%,transparent)] ring-[color:var(--hairline-brand)]":"ring-transparent hover:bg-[color:var(--accent)]"}`}><p className="font-mono text-xs text-[color:var(--brand)]">{item.codigo}</p><p className="mt-1 truncate text-sm">{item.remetente_nome} → {item.destinatario_nome}</p><p className="mt-1 text-[10px] text-muted-foreground">{item.cidade_origem_sigla} → {item.cidade_destino_sigla}</p></button>)}</div></aside>
      <main className="space-y-4">{error&&<p className="rounded-lg bg-[color:color-mix(in_oklab,var(--danger)_9%,transparent)] p-3 text-sm text-[color:var(--danger)]">{error}</p>}{detail?<><section className="surface-card p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-mono text-xs text-[color:var(--brand)]">{detail.codigo}</p><h3 className="mt-1 font-display text-xl">{detail.remetente_nome} → {detail.destinatario_nome}</h3><p className="mt-1 inline-flex items-center gap-2 text-sm text-muted-foreground"><MapPin className="h-4 w-4"/>{detail.cidade_origem_sigla} → {detail.cidade_destino_sigla} · {detail.viagem_codigo}</p></div><div className="text-right"><p className="big-numeric text-2xl text-[color:var(--brand)]">{brl(detail.valor_cobrado)}</p><StatusChip tone={detail.status_documental==="pronta"?"success":"warning"}>{detail.status_documental==="pronta"?"documentação pronta":detail.legado?"registro legado incompleto":"documentação pendente"}</StatusChip></div></div><div className="mt-4 flex flex-wrap gap-2"><Tag tone="neutral">{detail.total_volumes} volume(s)</Tag><Tag tone="neutral">{detail.peso_total} kg</Tag>{detail.documento_tipo&&<Tag tone="neutral">{detail.documento_tipo}</Tag>}{detail.foto_encomenda_url&&<Tag tone="neutral">foto vinculada</Tag>}</div>{detail.legado&&<p className="mt-4 rounded-lg bg-[color:color-mix(in_oklab,var(--warning)_10%,transparent)] p-3 text-xs text-[color:var(--warning)]">Registro preservado do modelo anterior. Campos ausentes não foram inventados; regularize a documentação no processo operacional.</p>}</section>
        <section className="surface-card p-5"><h3 className="font-semibold">Eventos registrados</h3>{events.length?<ol className="mt-4">{events.map((event,index)=><li key={`${event.id??event.entrega_protocolo}-${index}`} className="grid grid-cols-[24px_minmax(0,1fr)] gap-3"><div className="flex flex-col items-center"><span className="grid h-6 w-6 place-items-center rounded-full bg-[color:color-mix(in_oklab,var(--brand)_14%,transparent)] text-[color:var(--brand)]"><CheckCircle2 className="h-3.5 w-3.5"/></span>{index<events.length-1&&<span className="h-full w-px bg-[color:var(--hairline)]"/>}</div><div className="pb-5"><p className="text-sm font-medium">{event.entrega_protocolo?"Entrega confirmada":eventLabel(event.tipo)}</p><div className="mt-1 flex flex-wrap gap-x-4 gap-y-1 text-xs text-muted-foreground"><span className="inline-flex items-center gap-1"><Clock className="h-3 w-3"/>{formatDate(event.entregue_em??event.ocorrido_em??event.criado_em)}</span>{event.usuario_nome&&<span className="inline-flex items-center gap-1"><User className="h-3 w-3"/>{event.usuario_nome}</span>}<span className="inline-flex items-center gap-1"><Package className="h-3 w-3"/>volume {event.indice_volume}/{event.total_volumes}</span></div>{event.obs&&<p className="mt-2 text-xs text-muted-foreground">{event.obs}</p>}{event.entrega_protocolo&&<p className="mt-2 font-mono text-xs text-[color:var(--brand)]">{event.entrega_protocolo}</p>}</div></li>)}</ol>:<div className="mt-4 rounded-lg bg-[color:var(--surface-tint)] p-5 text-center text-sm text-muted-foreground"><Clock className="mx-auto mb-2 h-5 w-5"/>A encomenda foi cadastrada, mas ainda não possui evento físico de conferência, embarque ou entrega.</div>}</section>
        <section className="surface-card p-5"><div className="flex items-center gap-2"><FileText className="h-4 w-4 text-[color:var(--brand)]"/><h3 className="font-semibold">Evidências vinculadas</h3></div><div className="mt-3 grid gap-2 sm:grid-cols-2">{detail.evidencias.map((item)=><div key={item.id} className="rounded-lg bg-[color:var(--surface-tint)] p-3 ring-1 ring-[color:var(--hairline)]"><p className="text-sm font-medium">{labelEvidence(item.tipo)}</p><p className="mt-1 truncate text-xs text-muted-foreground">{item.arquivo_nome}</p><p className="mt-1 font-mono text-[9px] text-muted-foreground">SHA-256 {item.arquivo_hash.slice(0,16)}…</p></div>)}</div></section></>:<div className="surface-card grid min-h-72 place-items-center text-sm text-muted-foreground">Selecione uma encomenda para ver a trilha real.</div>}</main></div></div>;
}
function eventLabel(value:string|null){const labels:Record<string,string>={recebido:"Recebido",conferido:"Conferido",embarcado:"Embarcado",desembarcado:"Desembarcado",entregue:"Entregue",divergencia:"Divergência registrada"};return value?labels[value]??value.replaceAll("_"," "):"Volume cadastrado"}
function labelEvidence(value:string){return ({foto_encomenda:"Foto da encomenda",documento_nf:"Nota Fiscal",documento_dc:"Declaração de Conteúdo",assinatura_dc:"Assinatura da DC"} as Record<string,string>)[value]??value}
function formatDate(value:string){return new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(new Date(value))}
function normalize(value:string){return value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/\W/g,"")}
